-- MySQL dump 10.13  Distrib 5.6.9-rc, for Win64 (x86_64)
--
-- Host: localhost    Database: unused
-- ------------------------------------------------------
-- Server version	5.6.9-rc

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `gametips`
--

DROP TABLE IF EXISTS `gametips`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `gametips` (
  `Id` int(10) NOT NULL DEFAULT '0',
  `Tip` varchar(800) NOT NULL DEFAULT '',
  `Tip_loc2` varchar(800) NOT NULL DEFAULT '',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `Id` (`Id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `gametips`
--

LOCK TABLES `gametips` WRITE;
/*!40000 ALTER TABLE `gametips` DISABLE KEYS */;
/*!40000 ALTER TABLE `gametips` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Records of `gametips`
--

INSERT INTO `gametips` VALUES ('396', '|cffffd100Tip:|r Nearby questgivers that are awaiting your return are shown as a question mark on your mini-map.\r\n', '|cffffd100Astuce :|r Les donneurs de quête proches qui attendent votre retour sont indiqués par un point d\'interrogation sur votre minicarte.');
INSERT INTO `gametips` VALUES ('201', '|cffffd100Tip:|r Your spell casting can be cancelled by moving, jumping or hitting the escape key.\r\n\r\n', '|cffffd100Astuce :|r Vous pouvez annuler l\'incantation d\'un sort en vous déplaçant, en sautant ou en appuyant sur la touche d\'échappement.');
INSERT INTO `gametips` VALUES ('221', '|cffffd100Tip:|r Clicking on a player name in the chat window lets you send a private message to them.\r\n', '|cffffd100Astuce :|r Cliquer sur le nom d\'un joueur dans la fenêtre de discussion vous permet de lui envoyer un message privé.');
INSERT INTO `gametips` VALUES ('258', '|cffffd100Tip:|r If you <Shift>Click on a player name in the chat window it tells you additional information about them.\r\n', '|cffffd100Astuce :|r Si vous cliquez sur le nom d\'un personnage-joueur dans la fenêtre de discussion tout en appuyant sur la touche Maj, des informations supplémentaires à son sujet apparaîtront.');
INSERT INTO `gametips` VALUES ('222', '|cffffd100Tip:|r You can <Control>Click on an item to see how you would look wearing that item.\r\n', '|cffffd100Astuce :|r Vous pouvez cliquer sur un objet tout en appuyant sur <Ctrl> pour voir quelle serait votre apparence si vous le portiez.');
INSERT INTO `gametips` VALUES ('223', '|cffffd100Tip:|r An item with its name in gray is a poor quality item and generally can be sold to a vendor.\r\n', '|cffffd100Astuce :|r Un objet dont le nom apparaît en gris est de piètre qualité et peut le plus souvent être vendu sans regret à un marchand.');
INSERT INTO `gametips` VALUES ('224', '|cffffd100Tip:|r An item with its name in white is useful to players in some way and can be used or sold at the auction house.\r\n', '|cffffd100Astuce :|r Un objet dont le nom apparaît en blanc est utile aux joueurs d\'une certaine façon. Il peut être utilisé ou vendu à l\'hôtel des ventes.');
INSERT INTO `gametips` VALUES ('225', '|cffffd100Tip:|r You can send mail to other players or even to your other characters from any mailbox in game.\r\n', '|cffffd100Astuce :|r Vous pouvez envoyer du courrier aux autres joueurs ou même à vos autres personnages à partir de n\'importe quelle boîte aux lettres du jeu.');
INSERT INTO `gametips` VALUES ('226', '|cffffd100Tip:|r You can <Shift>Click on an item to place an item link into a chat message.\r\n', '|cffffd100Astuce :|r Vous pouvez cliquer sur un objet tout en appuyant sur la touche Maj pour créer un lien vers cet objet dans la fenêtre de discussion.');
INSERT INTO `gametips` VALUES ('384', '|cffffd100Tip:|r You can remove a friendly spell enhancement on yourself by right-clicking on the spell effect icon.', '|cffffd100Astuce :|r Vous pouvez annuler une amélioration amicale sur vous-même par un clic droit sur l’icône de l\'effet du sort.');
INSERT INTO `gametips` VALUES ('282', '|cffffd100Tip:|r When you learn a profession or secondary skill the button that allows you to perform that skill is found in the general tab of your spellbook.', '|cffffd100Astuce :|r Lorsque vous apprenez un métier ou une compétence secondaire, le bouton qui vous permet d\'exécuter cette compétence se trouve dans l\'onglet général de votre grimoire.');
INSERT INTO `gametips` VALUES ('227', '|cffffd100Tip:|r All of your action bars can have their hotkeys remapped in the key bindings interface.\r\n', '|cffffd100Astuce :|r Les raccourcis de toutes vos barres d\'actions peuvent être reconfigurés dans l\'interface d\'association de touches.');
INSERT INTO `gametips` VALUES ('229', '|cffffd100Tip:|r On your character sheet is a reputation tab that tells you your status with different groups.\r\n', '|cffffd100Astuce :|r Sur votre feuille de personnage se trouve un onglet de réputation qui vous indique votre statut auprès de différents groupes.');
INSERT INTO `gametips` VALUES ('263', '|cffffd100Tip:|r You can use the Tab key to select nearby enemies in front of you.\r\n', '|cffffd100Astuce :|r Vous pouvez utiliser la touche de tabulation pour sélectionner les ennemis proches se trouvant devant vous.');
INSERT INTO `gametips` VALUES ('321', '|cffffd100Tip:|r If you are having trouble finding something in a capital city, try asking a guard for directions.\r\n', '|cffffd100Astuce :|r Si vous avez des difficultés à trouver quelque chose dans une capitale, demandez à un garde de vous indiquer votre chemin.');
INSERT INTO `gametips` VALUES ('476', '|cffffd100Tip:|r You can use the V key to show enemy name plates above the enemy\'s head.  Name plates may help you keep track of enemy health or spell casting, or may make it easier to quickly change targets.', '|cffffd100Astuce :|r Vous pouvez utiliser la touche V pour montrer les informations essentielles concernant votre ennemi au-dessus de sa tête. Vous pouvez ainsi voir la vie de votre ennemi et les sorts qu\'il lance. Cela vous permet également de changer plus facilement de cible.');
INSERT INTO `gametips` VALUES ('470', '|cffffd100Tip:|r You can track many things, such as low-level quests or vendors by clicking on the magnifying glass near your mini map.', '|cffffd100Astuce :|r Vous pouvez afficher de nombreuses choses, comme les quêtes de bas-niveau ou les vendeurs, en cliquant sur la loupe près de votre mini-carte.');
INSERT INTO `gametips` VALUES ('230', '|cffffd100Tip:|r You can perform many fun actions with the emote system, for instance you can type /dance to dance.\r\n', '|cffffd100Astuce :|r Vous pouvez faire de nombreuses actions amusantes grâce au système des « emotes ». Par exemple, vous pouvez taper /danser pour danser.');
INSERT INTO `gametips` VALUES ('387', '|cffffd100Tip:|r A Blizzard employee will NEVER ask for your password.', '|cffffd100Astuce :|r Un employé de Blizzard ne vous demandera JAMAIS votre mot de passe.');
INSERT INTO `gametips` VALUES ('389', '|cffffd100Tip:|r You can only know two professions at a time, but you can learn all of the secondary skills (fishing, cooking and first-aid).', '|cffffd100Astuce :|r Vous ne pouvez pas exercer plus de deux professions à la fois, mais vous pouvez apprendre toutes les compétences secondaires (pêche, cuisine et secourisme).');
INSERT INTO `gametips` VALUES ('231', '|cffffd100Tip:|r The interface options menu <ESC> has lots of ways to customize your game play.\r\n', '|cffffd100Astuce :|r Le menu Interface <Echap> vous propose de nombreux moyens de modifier à votre convenance votre expérience du jeu.');
INSERT INTO `gametips` VALUES ('232', '|cffffd100Tip:|r You can turn on slow scrolling of quest text in the interface options menu.\r\n\r\n', '|cffffd100Astuce :|r Vous pouvez activer le lent déroulement du texte des quêtes dans le menu Interface.');
INSERT INTO `gametips` VALUES ('233', '|cffffd100Tip:|r Spend your talent points carefully as once your talents are chosen, you must spend gold to unlearn them.\r\n', '|cffffd100Astuce :|r Réfléchissez bien avant d\'utiliser vos points de talent, car une fois vos talents choisis, il faut dépenser de l\'or pour les désapprendre.');
INSERT INTO `gametips` VALUES ('234', '|cffffd100Tip:|r A mail icon next to the minimap means you have new mail.  Visit a mailbox to retrieve it.\r\n', '|cffffd100Astuce :|r Une icône Courrier à côté de votre minicarte vous indique que vous avez un nouveau message. Rendez-vous à une boîte aux lettres pour le récupérer.');
INSERT INTO `gametips` VALUES ('235', '|cffffd100Tip:|r You can add additional action bars to your game interface from the interface options menu.\r\n', '|cffffd100Astuce :|r Vous pouvez ajouter des barres d\'actions supplémentaires à votre interface de jeu à partir du menu Interface.');
INSERT INTO `gametips` VALUES ('236', '|cffffd100Tip:|r If you hold down <Shift> while right-clicking on a target to loot, you will automatically loot all items on the target.\r\n', '|cffffd100Astuce :|r Si vous maintenez la touche Maj enfoncée tout en cliquant droit sur une cible pour prendre le butin, vous prendrez automatiquement tout le butin se trouvant sur la cible.');
INSERT INTO `gametips` VALUES ('401', '|cffffd100Tip:|r Your character can eat and drink at the same time.', '|cffffd100Astuce :|r Votre personnage peut manger et boire simultanément.');
INSERT INTO `gametips` VALUES ('237', '|cffffd100Tip:|r If you enjoyed playing with someone from your realm, put them on your friends list!\r\n', '|cffffd100Astuce :|r Si vous avez aimé jouer avec quelqu\'un de votre royaume, ajoutez-le à votre liste d\'amis !');
INSERT INTO `gametips` VALUES ('406', '|cffffd100Tip:|r Use the Dungeon Finder tool to quickly travel to dungeons or to find more players for your dungeon group.\r\n\r\n\r\n', '|cffffd100Astuce :|r Utilisez l\'outil Donjons pour voyager rapidement vers un donjon ou pour trouver des membres supplémentaires pour votre groupe de donjon.');
INSERT INTO `gametips` VALUES ('239', '|cffffd100Tip:|r There are a number of different loot options when in a group. The group leader can right-click their own portrait to change the options.\r\n', '|cffffd100Astuce :|r Il existe différentes possibilités de partage du butin lorsque vous êtes en groupe. Le chef du groupe peut cliquer-droit sur son propre portrait pour changer d\'option.');
INSERT INTO `gametips` VALUES ('240', '|cffffd100Tip:|r If you never want to hear from another player again, you can /ignore them. You can always change your mind later.\r\n', '|cffffd100Astuce :|r Si vous ne voulez plus qu’un joueur vous parle, vous pouvez décider de le /ignorer. Vous pourrez toujours changer d’avis par la suite.');
INSERT INTO `gametips` VALUES ('241', '|cffffd100Tip:|r You can target members of your party with the function keys.  F1 targets you; F2 targets the second party member.\r\n', '|cffffd100Astuce :|r Vous pouvez cibler les membres de votre groupe à l\'aide des touches Fonction. F1 vous cible vous-même, F2 cible le deuxième membre du groupe.');
INSERT INTO `gametips` VALUES ('242', '|cffffd100Tip:|r Being polite while in a group with others will get you invited back!', '|cffffd100Astuce :|r Si vous êtes poli en groupe, vous aurez plus de chances d\'être invité à nouveau !');
INSERT INTO `gametips` VALUES ('341', '|cffffd100Tip:|r Remember to take all things in moderation (even World of Warcraft!)', '|cffffd100Astuce :|r Souvenez-vous que tout doit être apprécié avec modération (même World of Warcraft !)');
INSERT INTO `gametips` VALUES ('243', '|cffffd100Tip:|r You can click on a faction in the reputation pane to get additional information and options about that faction.\r\n\r\n', '|cffffd100Astuce :|r Pour obtenir des informations supplémentaires sur une faction, cliquez sur son nom dans l’onglet de réputation.');
INSERT INTO `gametips` VALUES ('244', '|cffffd100Tip:|r A monster with a silver dragon around its portrait is a rare monster with better than average treasure.\r\n', '|cffffd100Astuce :|r Un monstre avec un dragon argenté autour de son portrait est un monstre rare qui détient un trésor de valeur supérieure à la moyenne.');
INSERT INTO `gametips` VALUES ('245', '|cffffd100Tip:|r If you mouse over a chat pane it will become visible and you can Right Click on the chat pane tab for options.\r\n', '|cffffd100Astuce :|r Si vous passez votre souris au-dessus d\'une fenêtre de discussion, elle devient visible et vous pouvez cliquer-droit sur l\'onglet de la fenêtre pour avoir accès à différentes options.');
INSERT INTO `gametips` VALUES ('411', '|cffffd100Tip:|r Sharing an account with someone else can compromise its security.\r\n', '|cffffd100Astuce :|r Partager un compte avec quelqu\'un d\'autre peut compromettre sa sécurité.');
INSERT INTO `gametips` VALUES ('246', '|cffffd100Tip:|r You can display the duration of beneficial spells on you from the interface options menu.\r\n', '|cffffd100Astuce :|r Vous pouvez choisir d\'afficher la durée des améliorations dont vous bénéficiez dans le menu Interface.');
INSERT INTO `gametips` VALUES ('247', '|cffffd100Tip:|r You can lock your action bar so you don\'t accidentally move spells. This is done using the interface options menu.\r\n', '|cffffd100Astuce :|r Dans le menu Interface, vous pouvez verrouiller votre barre d\'actions afin d\'éviter de déplacer accidentellement des sorts.');
INSERT INTO `gametips` VALUES ('256', '|cffffd100Tip:|r You can change which buffs or debuffs are displayed on yourself or targets in order to get the information you need.\r\n', '|cffffd100Astuce :|r Vous pouvez définir quelles améliorations et affaiblissements afficher sur vous-même ou sur les autres joueurs pour obtenir les informations que vous souhaitez.');
INSERT INTO `gametips` VALUES ('248', '|cffffd100Tip:|r You can cast a spell on yourself without deselecting your current target by holding down <Alt> while pressing your hotkey.\r\n', '|cffffd100Astuce :|r Vous pouvez lancer un sort sur vous-même sans désélectionner votre cible actuelle en maintenant enfoncée la touche <Alt> lorsque vous appuyez sur le raccourci.');
INSERT INTO `gametips` VALUES ('398', '|cffffd100Tip:|r Ensure that all party members are on the same stage of an escort quest before beginning it.', '|cffffd100Astuce :|r Assurez-vous que tous les membres du groupe en sont à la même étape d’une quête d’escorte avant de déclencher la quête.');
INSERT INTO `gametips` VALUES ('405', '|cffffd100Tip:|r You\'re much less likely to encounter wandering monsters while following a road.', '|cffffd100Astuce :|r Vos chances de rencontrer des monstres errants sont réduites si vous restez sur les routes.');
INSERT INTO `gametips` VALUES ('250', '|cffffd100Tip:|r Killing guards gives no honor.', '|cffffd100Astuce :|r Tuer des gardes ne rapporte pas de points d\'honneur.');
INSERT INTO `gametips` VALUES ('254', '|cffffd100Tip:|r You can hide your interface with <Alt>Z and take screenshots with <Print Screen>.\r\n', '|cffffd100Astuce :|r <Alt>W vous permet de retirer et remettre votre interface pour faire des captures d\'écran avec <Impr écran>.');
INSERT INTO `gametips` VALUES ('251', '|cffffd100Tip:|r Typing /macro will bring up the interface to create macros.\r\n', '|cffffd100Astuce :|r Si vous tapez /macro, vous ouvrez l\'interface permettant de créer des macros.');
INSERT INTO `gametips` VALUES ('252', '|cffffd100Tip:|r Enemy players whose names appear in gray are much lower level than you are and will not give honor when killed.\r\n', '|cffffd100Astuce :|r Les personnages-joueurs ennemis dont le nom est affiché en gris sont d\'un niveau nettement inférieur au vôtre. Les tuer ne vous rapporte pas de points d\'honneur.');
INSERT INTO `gametips` VALUES ('253', '|cffffd100Tip:|r From the Raid UI you can drag a player to the game field to see their status or drag a class icon to see all members of that class.\r\n\r\n', '|cffffd100Astuce :|r Depuis l\'IU de raid, vous pouvez tirer le nom d\'un joueur vers le champ de jeu pour voir son statut ou tirer l\'icône d\'une classe pour voir tous les membres de cette classe.');
INSERT INTO `gametips` VALUES ('261', '|cffffd100Tip:|r  A blue question mark above a quest giver means the quest is repeatable. \r\n', '|cffffd100Astuce :|r Un point d\'interrogation bleu au-dessus d\'un donneur de quête indique que l\'on peut répéter la quête.');
INSERT INTO `gametips` VALUES ('262', '|cffffd100Tip:|r Use the assist button (F key) while targeting another player, and it will target the same target as that player.\r\n', '|cffffd100Astuce :|r Utilisez la touche de soutien (F) tout en ciblant un autre personnage-joueur et vous ciblerez le même adversaire que lui.');
INSERT INTO `gametips` VALUES ('281', '|cffffd100Tip:|r <Shift>Clicking on an item being sold by a vendor will let you select how many of that item you wish to purchase.', '|cffffd100Astuce :|r Si vous cliquez sur un objet vendu par un marchand tout en appuyant sur la touche Maj, vous pouvez choisir combien d\'exemplaires de cet objet vous souhaitez acheter.');
INSERT INTO `gametips` VALUES ('402', '|cffffd100Tip:|r Playing in a battleground on its holiday weekend increases your honor gained.\r\n', '|cffffd100Astuce :|r Participer à une bataille pendant la période d’appel aux armes du champ de bataille concerné augmente les gains d’honneur.');
INSERT INTO `gametips` VALUES ('400', '|cffffd100Tip:|r If you are having trouble fishing in an area, try attaching a lure to your fishing pole.', '|cffffd100Astuce :|r Si vous avez des difficultés pour pêcher dans une zone, essayez de mettre un appât sur votre canne à pêche.');
INSERT INTO `gametips` VALUES ('380', '|cffffd100Tip:|r You can view messages you previously sent in chat by pressing <Alt> and the up arrow key.', '|cffffd100Astuce :|r Vous pouvez revoir les messages que vous aviez envoyés précédemment dans la fenêtre de discussion en appuyant sur <Alt> et la touche flèche vers le haut.');
INSERT INTO `gametips` VALUES ('381', '|cffffd100Tip:|r You can Shift-Click on an item stack to split it into smaller stacks.', '|cffffd100Astuce :|r Cliquez sur une pile d’objets en appuyant sur la touche Maj pour la scinder en piles plus petites.');
INSERT INTO `gametips` VALUES ('382', '|cffffd100Tip:|r Pressing both mouse buttons simultaneously will make your character run.', '|cffffd100Astuce :|r Appuyez simultanément sur les deux boutons de la souris pour faire courir votre personnage.');
INSERT INTO `gametips` VALUES ('383', '|cffffd100Tip:|r When replying to a tell from a player (Default \'R\'), the <TAB> key cycles through people you have recently replied to.', '|cffffd100Astuce :|r Quand vous répondez à un message (touche par défaut « R »), vous pouvez sélectionner avec la touche <TAB> parmi les personnages à qui vous avez répondu récemment.');
INSERT INTO `gametips` VALUES ('388', '|cffffd100Tip:|r Clicking an item name that appears bracketed in chat will tell you more about the item.\r\n', '|cffffd100Astuce :|r Cliquez sur un nom d’objet entre crochets dans la fenêtre de discussion pour obtenir plus de détails sur cet objet.');
INSERT INTO `gametips` VALUES ('390', '|cffffd100Tip:|r It\'s considered polite to talk to someone before inviting them into a group, or opening a trade window.', '|cffffd100Astuce :|r Il est bien vu de parler à quelqu’un avant de l’inviter dans un groupe ou d’ouvrir une fenêtre d’échange.');
INSERT INTO `gametips` VALUES ('392', '|cffffd100Tip:|r Your items do not suffer durability damage when you are killed by an enemy player.', '|cffffd100Astuce :|r Vos objets ne subissent pas de dégâts de durabilité si vous vous faites tuer par un personnage-joueur de la faction adverse.');
INSERT INTO `gametips` VALUES ('393', '|cffffd100Tip:|r <Shift>click on a quest in your quest log to toggle quest tracking for that quest.\r\n', '|cffffd100Astuce :|r Cliquez sur une quête dans votre journal en appuyant sur la touche <Maj> pour afficher le suivi de cette quête.');
INSERT INTO `gametips` VALUES ('397', '|cffffd100Tip:|r The auction houses in each of your faction\'s major cities are linked together. \r\n', '|cffffd100Astuce :|r Les hôtels des ventes de chacune des villes principales de votre faction sont liés.');
INSERT INTO `gametips` VALUES ('394', '|cffffd100Tip:|r Nearby questgivers that are awaiting your return are shown as a yellow question mark on your mini-map.\r\n', '|cffffd100Astuce :|r Les donneurs de quête proches qui attendent votre retour sont indiqués par des points d\'interrogation jaunes sur votre minicarte.');
INSERT INTO `gametips` VALUES ('399', '|cffffd100Tip:|r Quests completed at maximum level award money instead of experience.\r\n', '|cffffd100Astuce :|r Les quêtes que vous accomplissez quand vous êtes au niveau maximum vous rapportent de l’argent à la place de l’expérience.');
INSERT INTO `gametips` VALUES ('403', '|cffffd100Tip:|r <Shift>-B will open all your bags at once.', '|cffffd100Astuce :|r Appuyez sur <Maj>-B pour ouvrir tous vos sacs d’un coup.');
INSERT INTO `gametips` VALUES ('404', '|cffffd100Tip:|r When interacting with other players a little kindness goes a long way! \r\n', '|cffffd100Astuce :|r Lors de vos interactions avec d’autres personnages, souvenez-vous qu’un minimum de courtoisie peut ouvrir bien des portes !');
INSERT INTO `gametips` VALUES ('407', '|cffffd100Tip:|r Bring your friends to Azeroth, but don\'t forget to go outside Azeroth with them as well.\r\n', '|cffffd100Astuce :|r Amenez vos amis en Azeroth, mais n’oubliez pas pour autant de les voir en dehors d’Azeroth.');
INSERT INTO `gametips` VALUES ('409', '|cffffd100Tip:|r If you keep an empty mailbox, the mail icon will let you know when you have new mail waiting!\r\n', '|cffffd100Astuce :|r Si vous videz régulièrement votre boîte à lettre, l’icône de courrier vous avertira en cas de nouveaux messages !');
INSERT INTO `gametips` VALUES ('410', '|cffffd100Tip:|r Never give another player your account information.', '|cffffd100Astuce :|r Ne donnez jamais les informations relatives à votre compte à un autre joueur.');
INSERT INTO `gametips` VALUES ('419', '|cffffd100Tip:|r When a player not in your group damages a monster before you do, it will display a gray health bar and you will get no loot or experience from killing it.\r\n', '|cffffd100Astuce :|r Lorsqu’un monstre est blessé par un personnage qui n’appartient pas à votre groupe, sa barre de vie devient grise. Il ne vous rapportera ni butin ni expérience même si vous le tuez.');
INSERT INTO `gametips` VALUES ('420', '|cffffd100Tip:|r You can see the spell that your current target is casting by turning on the \'Cast Bars\' options in the combat interface options tab.\r\n', '|cffffd100Astuce :|r Activer l’option « Barre de sorts », dans les options d’interface de combat, vous permet de voir le sort que votre cible actuelle est en train de lancer.');
INSERT INTO `gametips` VALUES ('422', '|cffffd100Tip:|r You can access the map either by clicking the map button in the upper right of the mini-map or by hitting the \'M\' key. The map can help you locate where you need to go to complete a quest.\r\n', '|cffffd100Astuce :|r Pour voir la carte, appuyez sur la touche « M » ou cliquez sur le bouton qui se trouve en haut à droite de la minicarte. La carte vous aide à localiser les endroits où vous pourrez achever une quête.');
INSERT INTO `gametips` VALUES ('423', '|cffffd100Tip:|r Many high level dungeons have a heroic mode setting. Heroic mode dungeons are tuned for higher level players and have improved loot.\r\n', '|cffffd100Astuce :|r De nombreux donjons de haut niveau ont un mode Héroïque. Lorsqu’ils sont joués en mode Héroïque, ils sont adaptés à des personnages de niveau plus élevé, et disposent de butins améliorés.');
INSERT INTO `gametips` VALUES ('424', '|cffffd100Tip:|r Spend your honor points for powerful rewards at the Champion\'s Hall (Alliance) or Hall of Legends (Horde).\r\n', '|cffffd100Astuce :|r Achetez de puissantes récompenses avec vos points d’honneur au Hall des champions (Alliance) ou au Hall des légendes (Horde).');
INSERT INTO `gametips` VALUES ('425', '|cffffd100Tip:|r The honor points you earn each day become available immediately. Check the PvP interface to see how many points you have to spend.\r\n', '|cffffd100Astuce :|r Les points d’honneur gagnés un jour sont disponibles immédiatement. Pour voir de combien de points vous disposez, consultez l’interface JcJ.');
INSERT INTO `gametips` VALUES ('412', '|cffffd100Tip:|r You can turn these tips off in the Interface menu.', '|cffffd100Astuce :|r Vous pouvez désactiver ces astuces dans le menu Interface.');
INSERT INTO `gametips` VALUES ('426', '|cffffd100Tip:|r Dungeon meeting stones can be used to summon absent party members.  It requires two players at the stone to do a summoning.\r\n', '|cffffd100Astuce :|r Les pierres de rencontre servent à invoquer les membres du groupe qui ne sont pas sur place. Pour cela, il faut que deux personnages se trouvent près de la pierre.');
INSERT INTO `gametips` VALUES ('427', '|cffffd100Tip:|r The Parental Controls section of the Account Management site offers tools to help you manage your play time.\r\n', '|cffffd100Astuce :|r La partie Contrôle parental du site de Gestion de compte vous propose des outils pour vous aider à gérer votre temps de jeu.');
INSERT INTO `gametips` VALUES ('428', '|cffffd100Tip:|r Quest items that are in the bank cannot be used to complete quests.\r\n', '|cffffd100Astuce :|r Les objets de quête qui se trouvent en banque ne peuvent être utilisés pour terminer une quête.');
INSERT INTO `gametips` VALUES ('429', '|cffffd100Tip:|r A quest marked as (Failed) in the quest log can be reacquired from the quest giver.\r\n', '|cffffd100Astuce :|r Une quête pour laquelle est indiqué un (Échec) dans le journal de quêtes peut être reprise auprès du personnage qui la proposait.');
INSERT INTO `gametips` VALUES ('430', '|cffffd100Tip:|r The number next to the quest name in your log is how many other party members are on that quest.\r\n', '|cffffd100Astuce :|r Le nombre qui apparaît à côté du nom d\'une quête dans le journal indique le nombre de personnes de votre groupe qui l\'ont aussi à accomplir.');
INSERT INTO `gametips` VALUES ('431', '|cffffd100Tip:|r You cannot advance quests other than (Raid) quests while you are in a raid group.\r\n', '|cffffd100Astuce :|r Lorsque vous faites partie d\'un groupe de raid, vous ne pouvez faire progresser que les quêtes marquées pour (Raid).');
INSERT INTO `gametips` VALUES ('432', '|cffffd100Tip:|r You cannot cancel your bids in the auction house so bid carefully.\r\n', '|cffffd100Astuce :|r Il n\'est pas possible d\'annuler vos enchères à l\'hôtel des ventes, placez-les avec prudence.');
INSERT INTO `gametips` VALUES ('433', '|cffffd100Tip:|r To enter a chat channel, type /join [channel name] and /leave [channel name] to exit.\r\n', '|cffffd100Astuce :|r Pour entrer sur un canal de discussion, tapez /rejoindre [nom du canal]. Pour le quitter, tapez /partir [nom du canal].');
INSERT INTO `gametips` VALUES ('434', '|cffffd100Tip:|r Mail will be kept for a maximum of 30 days before it disappears.\r\n', '|cffffd100Astuce :|r Le courrier est conservé 30 jours au maximum avant de disparaître.');
INSERT INTO `gametips` VALUES ('435', '|cffffd100Tip:|r Once you get a key, they can be found in a special key ring bag that is to the left of your bags.\r\n', '|cffffd100Astuce :|r Lorsque vous recevez une clé, elle est placée dans le trousseau de clés qui se trouve à gauche de vos autres sacs.');
INSERT INTO `gametips` VALUES ('437', '|cffffd100Tip:|r City Guards will often give you directions to other locations of note in the city.\r\n', '|cffffd100Astuce :|r Les gardes d\'une ville peuvent souvent vous indiquer où trouver certains endroits importants de la ville.');
INSERT INTO `gametips` VALUES ('438', '|cffffd100Tip:|r You can repurchase items you have recently sold to a vendor from the buyback tab.\r\n', '|cffffd100Astuce :|r Vous pouvez racheter les objets vendus récemment à un marchand grâce à l\'onglet de rachat.');
INSERT INTO `gametips` VALUES ('439', '|cffffd100Tip:|r A group leader can reset their instances or change dungeon difficulty by Right Clicking on their character portrait.', '|cffffd100Astuce :|r Le chef d\'un groupe peut réinitialiser ses instances ou en modifier la difficulté grâce au menu disponible par clic droit sur son portrait.');
INSERT INTO `gametips` VALUES ('440', '|cffffd100Tip:|r You can always get a new hearthstone from any innkeeper.\r\n', '|cffffd100Astuce :|r N\'importe quel aubergiste pourra toujours vous fournir une nouvelle pierre de foyer.');
INSERT INTO `gametips` VALUES ('441', '|cffffd100Tip:|r You can open a small map of the current zone either with Shift-M or as an option from the world map.', '|cffffd100Astuce :|r Vous pouvez afficher une petite carte de votre zone soit en appuyant sur Maj-M, soit en activant l\'option à partir de la carte du monde.');
INSERT INTO `gametips` VALUES ('442', '|cffffd100Tip:|r Players cannot dodge, parry, or block attacks that come from behind them.', '|cffffd100Astuce :|r Les personnages-joueurs ne peuvent pas esquiver, parer ou bloquer les attaques qui arrivent de derrière eux.');
INSERT INTO `gametips` VALUES ('444', '|cffffd100Tip:|r You can replace a gem that is already socketed into your item by dropping a new gem on top of it in the socketing interface.', '|cffffd100Astuce :|r Vous pouvez remplacer une gemme déjà sertie dans un objet en posant une nouvelle gemme par-dessus dans l\'interface de sertissage.');
INSERT INTO `gametips` VALUES ('445', '|cffffd100Tip:|r If you Right Click on a name in the combat log a list of options will appear.\r\n', '|cffffd100Astuce :|r Si vous cliquez droit sur un nom dans le journal de combat, une liste d\'options s\'affiche.');
INSERT INTO `gametips` VALUES ('446', '|cffffd100Tip:|r You can only have one Battle Elixir and one Guardian Elixir on you at a time.', '|cffffd100Astuce :|r Vous ne pouvez avoir qu\'un Elixir de bataille et un Elixir du Gardien actifs en même temps.');
INSERT INTO `gametips` VALUES ('447', '|cffffd100Tip:|r When you are mousing over an item, you can hold down the shift key and it will also show you the item of that type you have equipped.\r\n', '|cffffd100Astuce :|r Quand vous passez votre souris au-dessus d\'un objet, vous pouvez appuyer sur la touche Maj pour voir l\'objet de ce type que vous avez équipé.');
INSERT INTO `gametips` VALUES ('448', '|cffffd100Tip:|r You can have up to 10 characters per realm, with a maximum of 50 characters total across all realms. ', '|cffffd100Astuce :|r Vous pouvez posséder jusqu\'à 10 personnages par royaume, dans la limite de 50 personnages tous royaumes confondus.');
INSERT INTO `gametips` VALUES ('449', '|cffffd100Tip:|r You can reuse text that you have recently typed. Press Enter, then use <Alt> + Up Arrow to scroll through your previous messages. ', '|cffffd100Astuce :|r Vous pouvez réutiliser un texte que vous avez récemment écrit. Appuyez sur Entrée, puis appuyez sur la touche <Alt> et la flèche vers le haut pour faire défiler vos précédents messages.');
INSERT INTO `gametips` VALUES ('464', '|cffffd100Tip:|r You can use the Calendar to see upcoming holidays or plan events with your guild or friends.', '|cffffd100Astuce :|r Vous pouvez utiliser le calendrier pour visualiser les évènements saisonniers à venir ou pour organiser des évènements avec votre guilde ou vos amis.');
INSERT INTO `gametips` VALUES ('465', '|cffffd100Tip:|r You can Right Click on the Clock to set an alarm or display a stopwatch.', '|cffffd100Astuce :|r Vous pouvez cliquer droit sur l\'horloge pour paramétrer une alarme ou afficher un chronomètre.');
INSERT INTO `gametips` VALUES ('450', '|cffffd100Tip:|r Your mounts and non-combat companions can be accessed from the Pets tab on your character page.', '|cffffd100Astuce :|r Vos montures et vos familiers pacifiques se trouvent sur l’onglet « Familiers » de votre feuille de personnage.');
INSERT INTO `gametips` VALUES ('451', '|cffffd100Tip:|r Currencies, such as the ones collected from Battlegrounds or Heroic dungeons, are stored in the Currency Page.', '|cffffd100Astuce :|r Les monnaies, comme celles que l’on récupère sur les champs de bataille ou dans les donjons héroïques, sont conservées dans le panneau Monnaies.');
INSERT INTO `gametips` VALUES ('452', '|cffffd100Tip:|r Some vehicles can carry multiple passengers.', '|cffffd100Astuce :|r Certains véhicules peuvent transporter plusieurs passagers.');
INSERT INTO `gametips` VALUES ('466', '|cffffd100Tip:|r Characters with the Inscription profession can inscribe glyphs to improve some of your favorite spells and abilities.', '|cffffd100Astuce :|r Les personnages ayant pour profession la calligraphie peuvent créer des glyphes qui améliorent certains de vos sorts et techniques favoris.');
INSERT INTO `gametips` VALUES ('467', '|cffffd100Tip:|r If you\'re looking for something different to do, try to complete some of the more unusual Achievements.', '|cffffd100Astuce :|r Si vous souhaitez faire quelque chose de différent, tentez d\'accomplir des hauts faits inhabituels.');
INSERT INTO `gametips` VALUES ('468', '|cffffd100Tip:|r You can link quests, items, spells and achievements to chat messages by Shift-Left Clicking in your log.', '|cffffd100Astuce :|r Vous pouvez faire un lien dans vos messages de discussion vers des quêtes, des objets, des sorts et des hauts faits, en faisant Maj+clic gauche sur les éléments appropriés.');
INSERT INTO `gametips` VALUES ('469', '|cffffd100Tip:|r You can track progress on current quests or achievements.', '|cffffd100Astuce :|r Vous pouvez suivre la progression de vos quêtes et de vos hauts faits en cours de réalisation.');
INSERT INTO `gametips` VALUES ('453', '|cffffd100Tip:|r Flying mounts can be used in Outland once you attain the appropriate skill level of Riding and in Northrend after training Cold Weather Flying.', '|cffffd100Astuce :|r Les montures volantes peuvent être utilisées en Outreterre lorsque vous avez le niveau approprié en Monte, et en Norfendre lorsque vous avez appris à voler par temps froid.');
INSERT INTO `gametips` VALUES ('454', '|cffffd100Tip:|r Completing some Achievements may grant unique non-combat items as rewards.', '|cffffd100Astuce :|r Accomplir certains hauts faits donne accès à des récompenses, des objets uniques non liés au combat.');
INSERT INTO `gametips` VALUES ('455', '|cffffd100Tip:|r Items with bonus spell power improve both spell damage and healing.', '|cffffd100Astuce :|r Les objets possédant un bonus à la puissance des sorts augmentent à la fois les effets des sorts de dégâts et de soins.');
INSERT INTO `gametips` VALUES ('456', '|cffffd100Tip:|r Dealing damage, healing or casting spells can generate Threat against a creature.  Most creatures will attack the player with the highest Threat against them.', '|cffffd100Astuce :|r Infliger des dégâts, soigner ou lancer des sorts peut générer de la menace envers une créature. La plupart des créatures attaquent le joueur ayant la plus forte menace envers elles.');
INSERT INTO `gametips` VALUES ('457', '|cffffd100Tip:|r Creatures four levels above you can hit you with a Crushing Blow for extra damage.', '|cffffd100Astuce :|r Les créatures de quatre niveaux de plus que vous peuvent vous frapper avec un coup écrasant, qui inflige des dégâts supplémentaires.');
INSERT INTO `gametips` VALUES ('458', '|cffffd100Tip:|r Statistics track some interesting numbers related to your character, such as total food eaten and highest critical hit.', '|cffffd100Astuce :|r Les statistiques enregistrent certains chiffres intéressants sur votre personnage, comme la quantité de nourriture ingurgitée ou le plus gros coup critique infligé.');
INSERT INTO `gametips` VALUES ('459', '|cffffd100Tip:|r You can have your hair cut, colored or styled in a Barber Shop located in many cities.', '|cffffd100Astuce :|r Vous pouvez vous faire couper et colorer les cheveux dans les salons de coiffure situés dans plusieurs villes.');
INSERT INTO `gametips` VALUES ('460', '|cffffd100Tip:|r Recruiting a friend to World of Warcraft can provide rewards for both of you.', '|cffffd100Astuce :|r Parrainer un ami dans World of Warcraft vous permet à tous les deux d\'obtenir de belles récompenses.');
INSERT INTO `gametips` VALUES ('462', '|cffffd100Tip:|r You can set a Focus Frame by Right Clicking on a unit frame.  You can unlock a Focus Frame to move it anywhere around your screen.', '|cffffd100Astuce :|r Vous pouvez paramétrer un portrait de focalisation en cliquant droit sur le portrait d\'une unité. Vous pouvez déverrouiller le portrait de focalisation et le placer n\'importe où sur votre écran.');
INSERT INTO `gametips` VALUES ('461', '|cffffd100Tip:|r You can compare your Achievements to those of another player.', '|cffffd100Astuce :|r Vous pouvez comparer vos hauts faits à ceux d\'un autre joueur.');
INSERT INTO `gametips` VALUES ('463', '|cffffd100Tip:|r You can set an option to cast spells on yourself or on your Focus target by looking in Interface Options, Combat.', '|cffffd100Astuce :|r Vous pouvez paramétrer vos options pour lancer des sorts sur vous-même ou sur une cible focalisée dans les options d\'interface de combat.');
INSERT INTO `gametips` VALUES ('471', '|cffffd100Tip:|r A sanctuary is a town in which Player vs. Player combat is prohibited, such as Shattrath and Dalaran.', '|cffffd100Astuce :|r Un sanctuaire est une ville où les combats JcJ ne sont pas autorisés, comme Shattrath et Dalaran.');
INSERT INTO `gametips` VALUES ('472', '|cffffd100Tip:|r Improving your reputation with a faction can grant access to new quests or items.', '|cffffd100Astuce :|r Améliorer votre réputation auprès de diverses factions vous permet d\'accéder à de nouvelles quêtes et récompenses.');
INSERT INTO `gametips` VALUES ('473', '|cffffd100Tip:|r The Calendar can tell you when raids reset.', '|cffffd100Astuce :|r Le calendrier vous apprend quand vos raids sont remis à zéro.');
INSERT INTO `gametips` VALUES ('474', '|cffffd100Tip:|r Creatures cannot make critical hits with spells, but players can.', '|cffffd100Astuce :|r Les créatures ne peuvent pas infliger de coups critiques avec les sorts, contrairement aux joueurs.');
INSERT INTO `gametips` VALUES ('475', '|cffffd100Tip:|r Creatures can dodge attacks from behind, but players cannot.  Neither creatures nor players can parry attacks from behind.', '|cffffd100Astuce :|r Les créatures peuvent esquiver les attaques dans le dos, mais pas les joueurs. Ni les créatures, ni les joueurs ne peuvent parer les attaques dans le dos.');
INSERT INTO `gametips` VALUES ('479', '|cffffd100Tip:|r You can activate the Equipment Manager feature under Interface Controls to let you quickly swap to sets of gear that you find yourself using often.', '|cffffd100Astuce :|r Vous pouvez activer le Gestionnaire d\'équipement dans l\'écran d\'interface pour échanger rapidement des tenues et des armes que vous utilisez souvent.');
INSERT INTO `gametips` VALUES ('480', '|cffffd100Tip:|r Once you reach level 40, your class trainer can instruct you in Dual Talent Specialization. This feature allows you to swap out your talents, glyphs and action bars between two commonly used configurations.', '|cffffd100Astuce :|r Quand vous atteignez le niveau 40, votre maître de classe peut vous apprendre la double spécialisation des talents. Elle vous permet de changer rapidement vos talents, vos glyphes et vos barres d\'actions entre deux configurations que vous utilisez souvent.');
INSERT INTO `gametips` VALUES ('481', '|cffffd100Tip:|r You can enable Arena Enemy Frames to display the unit frames of the enemy team when in Arena matches.', '|cffffd100Astuce :|r Vous pouvez activer l\'option Portraits d\'ennemis en arène pour afficher les portraits des membres de l\'équipe ennemie dans les matchs d\'arène.');
INSERT INTO `gametips` VALUES ('482', '|cffffd100Tip:|r Under Interface Display is an option to Preview Talent Changes. If you select this option, you can try out various ways to spend talent points before saving the changes.', '|cffffd100Astuce :|r Dans les options d\'affichage de l\'interface, vous pouvez activer l\'Aperçu des modifications de talents. Si vous activez cette option, vous pourrez essayer différentes façons de dépenser vos points de talent avant de sauvegarder vos modifications.');
INSERT INTO `gametips` VALUES ('483', '|cffffd100Tip:|r If you press <Alt> while your cursor is over an item slot on your character, you can produce a list of items that can be equipped in that slot.', '|cffffd100Astuce :|r Si vous appuyez sur « Alt » lorsque le curseur est sur un emplacement d’objet dans votre feuille de personnage, vous verrez apparaître une liste d’objets dont vous pouvez vous équiper à cet emplacement.');
INSERT INTO `gametips` VALUES ('489', '|cffffd100Tip:|r If an enemy cast bar has a shield icon around it, that means you cannot interrupt the spell with your abilities.', '|cffffd100Astuce :|r Si la barre de sorts d’un ennemi est entourée d’une icône de bouclier, vous ne pouvez pas interrompre ce sort à l’aide de vos capacités.');
INSERT INTO `gametips` VALUES ('490', '|cffffd100Tip:|r Your guild can schedule Guild Events using the in-game calendar. You choose to sign up for these events rather than waiting for an invitation.', '|cffffd100Astuce :|r Votre guilde peut prévoir des Évènements de guilde à l’aide du calendrier en jeu. Vous pouvez choisir de vous y inscrire plutôt que d’attendre une invitation.');
INSERT INTO `gametips` VALUES ('491', '|cffffd100Tip:|r When the autocomplete feature suggests character names, you can use Tab or <Shift> Tab to select a name from the list.', '|cffffd100Astuce :|r Lorsque la fonctionnalité de remplissage automatique suggère des noms de personnages, appuyez sur Tab. ou Maj. + Tab. pour sélectionner un nom dans la liste.');
INSERT INTO `gametips` VALUES ('500', '|cffffd100Tip:|r Always verify that you are accessing an official Blizzard website whenever submitting account information.', '|cffffd100Astuce :|r Vérifiez toujours que vous êtes sur un site officiel de Blizzard lorsque vous indiquez vos informations de compte.');
INSERT INTO `gametips` VALUES ('501', '|cffffd100Tip:|r Emails from Blizzard will always end in either blizzard.com or battle.net.', '|cffffd100Astuce :|r Les emails envoyés par Blizzard proviennent toujours d\'une adresse se terminant par blizzard.com ou battle.net.');
INSERT INTO `gametips` VALUES ('502', '|cffffd100Tip:|r You can download free programs to regularly scan your machine for malicious software including keyloggers.', '|cffffd100Astuce :|r Vous pouvez télécharger des programmes gratuits qui analysent régulièrement votre machine à la recherche de logiciels malveillants, y compris les « keyloggers ».');
INSERT INTO `gametips` VALUES ('503', '|cffffd100Tip:|r For additional features and functionality, merge your World of Warcraft account into a Blizzard Battle.net account.', '|cffffd100Astuce :|r Pour accéder à des fonctionnalités avancées, fusionnez votre compte World of Warcraft et votre compte Blizzard Battle.net.');
INSERT INTO `gametips` VALUES ('504', '|cffffd100Tip:|r Using a Blizzard Authenticator or Battle.net Mobile Authenticator will help protect your World of Warcraft account from theft.', '|cffffd100Astuce :|r Utiliser un Blizzard Authenticator ou un Battle.net Mobile Authenticator vous aidera à protéger votre compte World of Warcraft des vols.');
INSERT INTO `gametips` VALUES ('505', '|cffffd100Tip:|r To avoid account theft, do not login to World of Warcraft on a computer that is shared with the general public. These machines can be infected with malicious software.', '|cffffd100Astuce :|r Pour éviter qu\'on vous vole votre compte, ne vous connectez pas à World of Warcraft depuis un ordinateur public. Ces ordinateurs peuvent être infectés par des logiciels malveillants.');
INSERT INTO `gametips` VALUES ('506', '|cffffd100Tip:|r Be wary of unofficial sites advertising paid World of Warcraft services. These may contain malicious software that can lead to account theft.', '|cffffd100Astuce :|r Méfiez-vous des sites non officiels proposant des services payants sur World of Warcraft. Ces sites peuvent contenir des logiciels malveillants entraînant le vol de votre compte.');
INSERT INTO `gametips` VALUES ('507', '|cffffd100Tip:|r To avoid account theft, do not use browser add-ons or features that allow scripts to be run in the background.', '|cffffd100Astuce :|r Pour éviter qu\'on vous vole votre compte, n\'utilisez pas d\'add-ons ou de fonctionnalités sur votre navigateur qui utilisent des scripts en tâche de fond.');
INSERT INTO `gametips` VALUES ('508', '|cffffd100Tip:|r Quest locations and questgivers can be seen on your map.', '|cffffd100Astuce :|r Les lieux de quêtes et les donneurs de quêtes sont visibles sur votre carte.');
INSERT INTO `gametips` VALUES ('509', '|cffffd100Tip:|r You can earn rewards for running random dungeons using the Dungeon Finder tool. You can go with a group of friends or use Dungeon Finder to find a dungeon group.', '|cffffd100Astuce :|r Vous pouvez obtenir des récompenses lorsque vous terminez des donjons aléatoires en utilisant l\'outil Donjons. Vous pouvez vous associer avec des amis ou utiliser l\'outil Donjons pour trouver un groupe.');
