-- MySQL dump 10.13  Distrib 5.6.9-rc, for Win64 (x86_64)
--
-- Host: localhost    Database: unused
-- ------------------------------------------------------
-- Server version	5.6.9-rc

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `spellmissilemotion`
--

DROP TABLE IF EXISTS `spellmissilemotion`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `spellmissilemotion` (
  `Id` int(10) NOT NULL DEFAULT '0',
  `Name` varchar(100) NOT NULL DEFAULT '',
  `ScriptBody` varchar(2000) NOT NULL DEFAULT '',
  `Flags` int(10) NOT NULL DEFAULT '0',
  `MissileCount` int(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `Id` (`Id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `spellmissilemotion`
--

LOCK TABLES `spellmissilemotion` WRITE;
/*!40000 ALTER TABLE `spellmissilemotion` DISABLE KEYS */;
/*!40000 ALTER TABLE `spellmissilemotion` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Records of `spellmissilemotion`
--

INSERT INTO `spellmissilemotion` VALUES ('13', 'Parabola', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .15\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('19', 'Spiral Vortex', 'local startAngle = 0\r\nlocal degreesPerSec = 180\r\nlocal maxMagnitude = 3\r\nlocal maxKickBack = 10\r\n\r\ntransAngle = startAngle + ((missileIndex / missileCount) * 360) + (time * degreesPerSec)\r\ntransMag = 1 - progress\r\ntransMag = (transMag * transMag * 2) - 1\r\ntransMag = (1 - (transMag * transMag))\r\ntransFront = transMag * -maxKickBack\r\ntransMag = transMag * maxMagnitude\r\n', '0', '7');
INSERT INTO `spellmissilemotion` VALUES ('20', 'Drunken Missiles', 'local maxMagnitude = 1.5\r\nlocal minSpeedScalar = .7\r\nlocal maxSpeedScalar = 1.5\r\n\r\nlocal magnitude = (progress * 1.9) - 1\r\nmagnitude = 1 - (magnitude * magnitude * magnitude * magnitude)\r\n\r\ntransRight = (sin((rand1 * 1000) + (time * 1000)) + cos((rand2 * 1000) + (time * 200))) * magnitude\r\ntransUp = (sin((rand2 * 1000) + (time * 700)) + cos((rand1 * 1000) + (time * 300))) * magnitude\r\nspeedScalar = minSpeedScalar + ((maxSpeedScalar - minSpeedScalar) * rand3)\r\n', '0', '5');
INSERT INTO `spellmissilemotion` VALUES ('22', 'Metawheel', 'local outerWheelSpinRate = 600\r\nlocal outerWheelMag = 1.5\r\nlocal innerWheelSpinRate = 800\r\nlocal innerWheelMagBase = .75\r\nlocal innerWheelMagVariance = .25\r\nlocal innerWheelOscillateRate = 300\r\n\r\ntransAngle = time * outerWheelSpinRate\r\ntransMag = outerWheelMag * (1 - progress)\r\nlocal innerMag = innerWheelMagBase + (innerWheelMagVariance * sin(time * innerWheelOscillateRate))\r\nif (missileIndex > 0) then\r\n	local anglePerMissile = 360 / (missileCount - 1)\r\n	transRight = innerMag * cos((time * innerWheelSpinRate) + (missileIndex * anglePerMissile))\r\n	transUp = innerMag * sin((time * innerWheelSpinRate ) + (missileIndex * anglePerMissile))\r\nend', '0', '4');
INSERT INTO `spellmissilemotion` VALUES ('23', 'Forward Spin', 'local spinRate = 720\r\n\r\nmodelPitch = time * spinRate', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('24', 'Boomerang', 'local angle = 90\r\nlocal maxMagnitude = startDistance * .2\r\nlocal spinRate = 720\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\nmodelYaw = time * spinRate', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('25', 'Spinning Wave', 'local startAngle = 0\r\nlocal finalAngle = 720\r\nlocal wavesPerSec = 2\r\nlocal maxMagnitude = 3\r\n\r\ntransAngle = startAngle + ((finalAngle - startAngle) * progress)\r\ntransMag = sin(time * wavesPerSec * 360) * maxMagnitude', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('26', 'Wave Beam', 'local waveHeight = .8\r\nlocal wavesPerSec = 4\r\n\r\ntransUp = waveHeight * sin(time * wavesPerSec * 360)', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('35', 'Glaive', 'local spinRate = 360\r\nlocal angle = 90\r\nlocal maxMagnitude = startDistance * .1\r\n\r\nmodelYaw = 90\r\nmodelRoll = time * spinRate\r\nmodelPitch = 90\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('36', 'Meteor Strike', 'local magnitude = totalDistance * .5\r\n\r\ntransUp = magnitude * ( 1 - progress )\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('37', 'Orbital Strike', 'local magnitude = totalDistance * 2\r\n\r\ntransUp = magnitude * ( 1 - progress )\r\ntransFront = distanceToImpactPos\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('38', 'Forward Spin + Parabola', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .15\r\nlocal spinRate = 360\r\n\r\nmodelPitch = time * spinRate\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('39', 'Spirit Fountain', '--\r\n-- This is actually more like a heat-seeking missile\r\n-- That always misses. \r\n-- However, if you use it with a Nearby-Circumference (Dest)\r\n-- It looks awesome! \r\n-- Check out 37099 for an example.\r\n--\r\nlocal angle = 0\r\nlocal maxMagnitude = startDistance*.75\r\n\r\ntransAngle = angle\r\n\r\nif ( progress > .5 ) then\r\n	transFront = (progress) / 2\r\nelse\r\n	transFront = ((progress) * 1.5 - 0.5 )\r\nend\r\n\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n	\r\ntransFront = transFront * totalDistance', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('40', 'Fountain', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .75\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n\r\ntransFront = -distanceToFirePos * (1 - progress)', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('41', 'Rocket Spiral', 'local startAngle = 0\r\nlocal degreesPerSec = 180\r\nlocal maxMagnitude = 3\r\nlocal maxKickBack = 10\r\n\r\ntransAngle = startAngle + ((missileIndex / missileCount) * 360) + (time * degreesPerSec)\r\ntransMag = 1 - progress\r\ntransMag = (transMag * transMag * 2) - 1\r\ntransMag = (1 - (transMag * transMag))\r\ntransFront = transMag * -maxKickBack\r\ntransMag = transMag * maxMagnitude\r\n\r\n-- Add Upward Arc\r\ntransUp = (progress * 2) - 1\r\ntransUp = (1 - (transUp * transUp)) * startDistance * .15\r\n\r\ntransFront = transFront + -distanceToFirePos * (1 - progress)', '0', '7');
INSERT INTO `spellmissilemotion` VALUES ('61', 'Shrink', 'scale = 1 - progress', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('62', 'Grow', 'scale = progress', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('81', 'Spiral Vortex (3 Missiles)', 'local startAngle = 0\r\nlocal degreesPerSec = 180\r\nlocal maxMagnitude = 3\r\nlocal maxKickBack = 10\r\n\r\ntransAngle = startAngle + ((missileIndex / missileCount) * 360) + (time * degreesPerSec)\r\ntransMag = 1 - progress\r\ntransMag = (transMag * transMag * 2) - 1\r\ntransMag = (1 - (transMag * transMag))\r\ntransFront = transMag * -maxKickBack\r\ntransMag = transMag * maxMagnitude\r\n', '0', '3');
INSERT INTO `spellmissilemotion` VALUES ('101', 'Roll (Clockwise)', 'local spinRate = 720\r\n\r\nmodelRoll = time * spinRate', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('121', 'Snake', 'local waveHeight = .8\r\nlocal wavesPerSec = 2\r\n\r\ntransRight = waveHeight * sin(time * wavesPerSec * 360) * ( 1 - progress ) * 2', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('122', 'Snake (half frequency)', 'local waveHeight = .8\r\nlocal wavesPerSec = 1\r\n\r\ntransRight = waveHeight * sin(time * wavesPerSec * 360) * ( 1 - progress ) * 2', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('123', 'Spiral Vortex (2 Missiles)', 'local startAngle = 0\r\nlocal degreesPerSec = 180\r\nlocal maxMagnitude = 3\r\nlocal maxKickBack = 10\r\n\r\ntransAngle = startAngle + ((missileIndex / missileCount) * 360) + (time * degreesPerSec)\r\ntransMag = 1 - progress\r\ntransMag = (transMag * transMag * 2) - 1\r\ntransMag = (1 - (transMag * transMag))\r\ntransFront = transMag * -maxKickBack\r\ntransMag = transMag * maxMagnitude\r\n', '0', '2');
INSERT INTO `spellmissilemotion` VALUES ('124', 'Parabola (-90 Pitch)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .15\r\nmodelPitch = -90\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('125', 'Parabola (-90 to -45) (Flag Throw)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .15\r\nmodelPitch = -90 + 45 * progress\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('141', 'Grow (x3)', 'scale = 3 * progress', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('142', 'Booterang', 'local angle = 90\r\nlocal maxMagnitude = startDistance * .2\r\nlocal spinRate = 720\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\nmodelYaw = time * spinRate\r\nmodelPitch = 90', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('161', 'Spin Around Caster', 'local outerWheelSpinRate = 360 	-- 1 spin / sec\r\nlocal outerWheelMag = 2			-- 1 yard\r\nlocal missileAngle = outerWheelSpinRate * time\r\n\r\nif (missileIndex > 0) then\r\n	--local anglePerMissile = 360 / (missileCount - 1)\r\n	--missileAngle = missileAngle + anglePerMissile * missileIndex\r\nend\r\n\r\ntransFront = outerWheelMag * cos ( missileAngle )\r\ntransRight = outerWheelMag * sin ( missileAngle )\r\ntransUp = -distanceToFirePos', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('162', 'Spin Around Caster  (3)', 'local outerWheelSpinRate = 360 	-- 1 spin / sec\r\nlocal outerWheelMag = 2.5			-- 1 yard\r\nlocal missileAngle = outerWheelSpinRate * time\r\n\r\nif (missileIndex > 0) then\r\n	local anglePerMissile = 360 / (missileCount)\r\n	missileAngle = missileAngle + anglePerMissile * missileIndex\r\nend\r\n\r\ntransFront = outerWheelMag * cos ( missileAngle )\r\ntransRight = outerWheelMag * sin ( missileAngle )\r\ntransUp = -distanceToFirePos', '0', '3');
INSERT INTO `spellmissilemotion` VALUES ('163', 'Spin Around Caster Slow (3)', 'local outerWheelSpinRate = 180 	-- 1 spin / sec\r\nlocal outerWheelMag = 2.5			-- 1 yard\r\nlocal missileAngle = outerWheelSpinRate * time\r\n\r\nif (missileIndex > 0) then\r\n	local anglePerMissile = 360 / (missileCount)\r\n	missileAngle = missileAngle + anglePerMissile * missileIndex\r\nend\r\n\r\ntransFront = outerWheelMag * cos ( missileAngle )\r\ntransRight = outerWheelMag * sin ( missileAngle )\r\ntransUp = -distanceToFirePos', '0', '3');
INSERT INTO `spellmissilemotion` VALUES ('181', 'Spiral (3 Missiles)', 'local outerWheelSpinRate = 180 	-- 1 spin / sec\r\nlocal outerWheelMag = 2.5			-- 1 yard\r\nlocal missileAngle = outerWheelSpinRate * time\r\n\r\nif (missileIndex > 0) then\r\n	local anglePerMissile = 360 / (missileCount)\r\n	missileAngle = missileAngle + anglePerMissile * missileIndex\r\nend\r\n\r\ntransFront = outerWheelMag * cos ( missileAngle )\r\ntransRight = outerWheelMag * sin ( missileAngle )\r\n', '0', '3');
INSERT INTO `spellmissilemotion` VALUES ('182', 'Spiral Inward (3 Missiles)', 'local outerWheelSpinRate = 180 	-- 1 spin / sec\r\nlocal outerWheelMag = 2.5			-- 1 yard\r\nlocal missileAngle = outerWheelSpinRate * time\r\n\r\nif (missileIndex > 0) then\r\n	local anglePerMissile = 360 / (missileCount)\r\n	missileAngle = missileAngle + anglePerMissile * missileIndex\r\nend\r\n\r\ntransFront = outerWheelMag * cos ( missileAngle ) * (1 - progress) * 2\r\ntransRight = outerWheelMag * sin ( missileAngle ) * (1 - progress) * 2\r\n', '0', '3');
INSERT INTO `spellmissilemotion` VALUES ('201', 'Axe Boomerang', 'local angle = -90\r\nlocal maxMagnitude = startDistance * .2\r\nlocal spinRate = 720\r\n\r\nmodelRoll = 90\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\nmodelYaw = time * spinRate', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('202', 'Axe Boomerang Return', 'local angle = 90\r\nlocal maxMagnitude = startDistance * .2\r\nlocal spinRate = 720\r\n\r\nmodelRoll = 90\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\nmodelYaw = time * spinRate\r\n\r\ntransFront = distanceToImpactPos - distanceToFirePos', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('221', 'Black Temple - Glaive Throw (Illidan)', 'modelRoll = time * 90', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('222', 'Black Temple - Glaives Return (Illidan)', 'modelRoll = time * 90', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('223', 'Rotation Test', 'local angle = 90\r\nlocal maxMagnitude = startDistance * .2\r\nlocal yawSpin = 1080\r\n\r\ntransAngle = angle\r\n--transMag = (progress * 2) - 1\r\n--transMag = (1 - (transMag * transMag)) * maxMagnitude\r\n--modelYaw = time * yawSpin\r\n--modelRoll = progress * 90\r\nmodelRoll = time * 500', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('224', 'Parabola (High)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .30\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('225', 'Spiral', 'local spinRate = 720\r\n\r\nmodelRoll = time * spinRate', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('226', 'Soul Vortex (3 Missiles)', 'local startAngle = 0\r\nlocal degreesPerSec = 180\r\nlocal maxMagnitude = 3\r\nlocal maxKickBack = 10\r\n\r\n--progress = 1 - progress\r\n\r\ntransAngle = startAngle + ((missileIndex / missileCount) * 360) + (time * degreesPerSec)\r\ntransMag = progress\r\ntransMag = (transMag * transMag * 2) - 1\r\ntransMag = (1 - (transMag * transMag))\r\ntransFront = transMag * -maxKickBack\r\ntransMag = transMag * maxMagnitude\r\n\r\n--transUp = distanceToImpactPos - distanceToFirePos', '0', '3');
INSERT INTO `spellmissilemotion` VALUES ('227', 'Black Temple - Akama Soul Retrieve (Do Not Reuse)', 'local startAngle = 0\r\nlocal degreesPerSec = 180\r\nlocal maxMagnitude = 3\r\nlocal maxKickBack = 10\r\n\r\ntransAngle = startAngle + ((missileIndex / missileCount) * 360) + (time * degreesPerSec)\r\ntransUp = distanceToImpactPos - distanceToFirePos\r\ntransMag = 10 * (1-progress) * (1-progress)\r\n\r\ntransFront = distanceToImpactPos * (1 - progress) * (1 - progress)', '0', '3');
INSERT INTO `spellmissilemotion` VALUES ('241', 'Multi-shot Parabola (8 Missiles)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .50\r\nlocal spread = 5\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n\r\ntransRight = (rand1 - 0.5) * spread * progress\r\ntransUp = (rand2 - 0.5) * spread * progress', '0', '8');
INSERT INTO `spellmissilemotion` VALUES ('261', 'Grow (1 -> 3)', 'scale = 1 + 2 * progress', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('321', 'Grow (1 -> 3) - Model Reversed', 'scale = 1 + 2 * progress\r\nmodelYaw = 180', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('341', 'Forward Spin + Parabola (High)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .30\r\nlocal spinRate = 360\r\n\r\nmodelPitch = time * spinRate\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('361', 'Parabola (Top Spin)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .15\r\nlocal spinRate = 720\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n\r\nmodelYaw = time * spinRate\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('362', 'Parabola (Pitch Spin)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .15\r\nlocal spinRate = 720\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n\r\nmodelPitch = time * spinRate\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('381', 'Test Missile - LAB', 'local startAngle = 0\r\nlocal degreesPerSec = 720\r\nlocal maxMagnitude = 1\r\nlocal maxKickBack = 10\r\n\r\ntransAngle = startAngle + ((missileIndex / missileCount) * 360) + (time * degreesPerSec)\r\ntransMag = 1 - progress\r\ntransMag = (transMag * transMag * 2) - 1\r\ntransMag = (1 - (transMag * transMag))\r\ntransFront = transMag * -maxKickBack\r\ntransMag = transMag * maxMagnitude\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('382', 'Possessed Knives', 'speedScalar = 0.1 + 35 * progress * progress\r\ntransUp  = (1.4 - 2 * rand1) * (1 - progress)\r\ntransRight  = (1 - 2 * rand2) * (1 - progress)', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('383', 'Twin Wave - Horizontal', '\r\nlocal waveHeight = 1.5\r\nlocal wavesPerSec = 0.7\r\n\r\nif (missileIndex == 0) then\r\ntransRight = waveHeight * sin(time * wavesPerSec * 360)\r\nend\r\n\r\nif (missileIndex == 1) then\r\ntransRight = - waveHeight * sin(time * wavesPerSec * 360)\r\nend', '0', '2');
INSERT INTO `spellmissilemotion` VALUES ('384', 'Twin Waves - Double', '\r\nlocal waveHeight = 1.5\r\nlocal wavesPerSec = 0.7\r\n\r\nif (missileIndex == 0) then\r\ntransRight = waveHeight * sin(time * wavesPerSec * 360)\r\nend\r\n\r\nif (missileIndex == 1) then\r\ntransRight = - waveHeight * sin(time * wavesPerSec * 360)\r\nend\r\n--[[\r\nif (missileIndex == 2) then\r\ntransUp = waveHeight * sin(time * wavesPerSec * 360) /2\r\nend\r\n\r\nif (missileIndex == 3) then\r\ntransUp = - waveHeight * sin(time * wavesPerSec * 360) /2\r\nend ]]', '0', '4');
INSERT INTO `spellmissilemotion` VALUES ('385', 'Split Four Ways', '\r\nlocal spread = 1.2\r\nlocal distanceToFireMin = 5\r\nlocal distanceToFireMax = 7\r\nlocal spreadSpeed = 0.1\r\nlocal finalSpeed = 1.5\r\n\r\nif ( distanceToFirePos > distanceToFireMin and distanceToFirePos < distanceToFireMax ) then\r\n   speedScalar = spreadSpeed\r\n   if (missileIndex == 0) then\r\n   transUp = spread * ( distanceToFirePos - distanceToFireMin ) / ( distanceToFireMax - distanceToFireMin )\r\n   end\r\n   if (missileIndex == 1) then\r\n   transUp = -spread * ( distanceToFirePos - distanceToFireMin   ) / ( distanceToFireMax - distanceToFireMin )\r\n   end\r\n   if (missileIndex == 2) then\r\n   transRight = spread * ( distanceToFirePos - distanceToFireMin   ) / ( distanceToFireMax - distanceToFireMin )\r\n   end\r\n   if (missileIndex == 3) then\r\n   transRight = -spread * ( distanceToFirePos - distanceToFireMin    ) / ( distanceToFireMax - distanceToFireMin )\r\n   end\r\nend\r\n\r\nif ( distanceToFirePos > distanceToFireMax ) then\r\n   speedScalar = finalSpeed\r\n   if (missileIndex == 0) then\r\n   transUp = spread\r\n   end\r\n   if (missileIndex == 1) then\r\n   transUp = -spread\r\n   end\r\n   if (missileIndex == 2) then\r\n   transRight = spread\r\n   end\r\n   if (missileIndex == 3) then\r\n   transRight = -spread\r\n   end\r\nend\r\n', '0', '4');
INSERT INTO `spellmissilemotion` VALUES ('386', 'Possessed Knives x8', 'speedScalar = 0.1 + 35 * progress * progress\r\ntransUp  = (1.4 - 2 * rand1) * (1 - progress)\r\ntransRight  = (1 - 2 * rand2) * (1 - progress)', '0', '8');
INSERT INTO `spellmissilemotion` VALUES ('401', 'Spin (Roll) - 1080', 'local spinRate = 1080\r\n\r\nmodelRoll = time * spinRate', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('421', 'Zul\'Aman - Skull Throw', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .15\r\nlocal spinRate = 720\r\n\r\nmodelPitch = time * spinRate\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('441', 'Forward Spin + Parabola (Very High)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .90\r\nlocal spinRate = 360\r\n\r\nmodelPitch = time * spinRate\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('482', 'Soul Vortex (3 Missiles - No Kickback)', 'local startAngle = 0\r\nlocal degreesPerSec = 180\r\nlocal maxMagnitude = 2.5\r\nlocal maxKickBack = 0\r\n\r\n--progress = 1 - progress\r\n\r\ntransAngle = startAngle + ((missileIndex / missileCount) * 360) + (time * degreesPerSec)\r\ntransMag = progress\r\ntransMag = (transMag * transMag * 2) - 1\r\ntransMag = (1 - (transMag * transMag))\r\ntransFront = transMag * -maxKickBack\r\ntransMag = transMag * maxMagnitude\r\n\r\n--transUp = distanceToImpactPos - distanceToFirePos', '0', '3');
INSERT INTO `spellmissilemotion` VALUES ('501', 'Parabola (Low)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .10\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('521', 'Parabola (Top Spin, High)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .30\r\nlocal spinRate = 720\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n\r\nmodelYaw = time * spinRate', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('541', 'Crazy Launch (1 Missile)', 'local outerWheelSpinRate = 1     -- 180 = 1 spin / sec\r\nlocal outerWheelMag = 1\r\nlocal missileAngle = 1\r\n\r\nouterWheelSpinRate = 360 - 400 * (progress)\r\nspeedScalar = sin(100 * progress) + 0.1\r\nmissileAngle = outerWheelSpinRate * time\r\nouterWheelMag = 10 * sin (500 * progress)\r\ntransFront = outerWheelMag * cos ( missileAngle )\r\ntransRight = outerWheelMag * sin ( missileAngle )\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('542', 'Parabola (Very High)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .60\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('561', 'Meandering Missile (1)', 'local maxMagnitude = 1.0\r\nlocal minSpeedScalar = 1.0\r\nlocal maxSpeedScalar = 1.0\r\nlocal randscalar = 100\r\nlocal timescalar = 50\r\n \r\nlocal angle = 0\r\nlocal maxArcMagnitude = startDistance * .35\r\n\r\nlocal magnitude = (progress * 1.9) - 1\r\n\r\nmagnitude = 1 \r\n\r\ntransRight = (sin((rand1 * randscalar * progress) + (time * randscalar)) + sin((rand2 * randscalar * progress) + (time * timescalar))) * magnitude\r\ntransUp = (sin((rand2 * randscalar * progress) + (time * randscalar)) + sin((rand1 * randscalar * progress) + (time * timescalar))) * magnitude\r\nspeedScalar = minSpeedScalar + ((maxSpeedScalar - minSpeedScalar) * rand3)\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxArcMagnitude\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('581', 'Meandering Missile Soul (1)', 'local maxMagnitude = 1.0\r\nlocal minSpeedScalar = 1.0\r\nlocal maxSpeedScalar = 1.0\r\nlocal randscalar = 100\r\nlocal timescalar = 50\r\n \r\nlocal angle = 0\r\nlocal maxMagnitude = startDistance * .35\r\n\r\nlocal magnitude = (progress * 1.9) - 1\r\n\r\nlocal Xmagnitude = 4 \r\nlocal Ymagnitude = 2\r\n\r\ntransRight = (sin((rand1 * randscalar * progress)+ (time * randscalar)) + sin((rand2 * randscalar * progress))) * Xmagnitude\r\ntransUp = (sin((rand2 * randscalar * progress) + (time * randscalar)) + sin((rand1 * randscalar * progress) + (time * timescalar))) * Ymagnitude\r\ntransUp = transUp - 0\r\nspeedScalar = minSpeedScalar + ((maxSpeedScalar - minSpeedScalar) * rand3)\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('601', 'Time-Warped Shot', '\r\nlocal slowProgressStart = 0.4\r\nlocal slowProgressEnd = 0.65\r\nlocal slowSpeed = 0.3\r\nlocal finalSpeed = 6\r\n\r\nspeedScalar = finalSpeed\r\n\r\nif ( progress > slowProgressStart and progress < slowProgressEnd ) then\r\n   speedScalar = slowSpeed\r\nend\r\n\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('621', 'Parabola (Pitch and Yaw Spin, High Altitude)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * 1\r\nlocal spinRateP = 180\r\nlocal spinRateY = 45\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n\r\n\r\nmodelPitch = time * spinRateP\r\nmodelYaw = time * spinRateY', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('641', 'Multi-Shot (3 Missiles)', '-- spread out as the missiles travel\r\nlocal outerWheelMag = 1.5 * progress\r\nlocal missileAngle\r\n\r\n\r\nif (missileIndex > 0) then\r\n	local anglePerMissile = 360 / (missileCount)\r\n	transAngle = anglePerMissile * missileIndex\r\nend\r\n\r\ntransMag = outerWheelMag\r\n', '0', '3');
INSERT INTO `spellmissilemotion` VALUES ('661', 'Big to Small to Big Scale', 'local m1x=0.4    --the first progress point where the missile is smallest\r\nlocal m1y=0.4    --the scale of the missile at the point above\r\n\r\nlocal m2x=0.6    --the first progress opint where the missile begins growing again\r\nlocal m2y=0.4    --the scale of the missile at the point above\r\n\r\n\r\nlocal slope\r\nlocal intercept\r\nif (progress <m1x) then\r\n                slope=(1-m1y)/(0-m1x)\r\n                intercept=1\r\nelseif (progress<m2x) then\r\n                slope=(m1y-m2y)/(m1x-m2x)\r\n                intercept=m1y-slope*m1x\r\nelse\r\n                slope=(m2y-1)/(m2x-1)\r\n                intercept=1-slope\r\nend\r\nscale=slope*progress+intercept\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('681', 'Creature - Drain Power Effect (Malacrass)', 'local startAngle = 0\r\nlocal degreesPerSec = 720\r\nlocal maxMagnitude = 1\r\nlocal maxKickBack = 10\r\n\r\ntransAngle = startAngle + ((missileIndex / missileCount) * 360) + (time * degreesPerSec)\r\ntransMag = 1 - progress\r\ntransMag = (transMag * transMag * 2) - 1\r\ntransMag = (1 - (transMag * transMag))\r\ntransFront = transMag * -maxKickBack\r\ntransMag = transMag * maxMagnitude\r\n', '0', '5');
INSERT INTO `spellmissilemotion` VALUES ('701', 'Forward Spin (Fast)', 'local spinRate = 1440\r\n\r\nmodelPitch = time * spinRate', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('721', 'Triple Parabola (Low)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .10\r\n\r\ntransAngle = angle\r\nprogress = math.fmod(progress * 3, 1)\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('722', 'Triple Parabola (Low, Falloff) ', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .10\r\n\r\ntransAngle = angle\r\nprogress = math.fmod(progress * 3, 1)\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\ntransMag = transMag * (1 - progress)', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('741', 'Grow (1 -> 10)', 'scale = 10 * progress', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('761', 'Paper Airlplane, Flying Machine ', '\r\nlocal minSpeedScalar = 1.0\r\nlocal maxSpeedScalar = 1.0\r\nlocal randscalar = 100\r\nlocal timescalar = 50\r\n \r\nlocal angle = 0\r\nlocal maxMagnitude = startDistance * .20\r\n\r\nlocal magnitude = (progress * 1.9) - 1\r\n\r\nlocal Xmagnitude = 4 \r\nlocal Ymagnitude = 2\r\n\r\n\r\nlocal modProgress = 4*(-1*(progress*progress) + progress)\r\n\r\ntransRight = (sin((rand1 * randscalar * modProgress)+ (time * randscalar * modProgress)) + sin((rand2 * randscalar * modProgress))) * Xmagnitude\r\ntransUp = (sin((rand2 * randscalar * modProgress) + (time * randscalar)) + sin((rand1 * randscalar * modProgress) + (time * timescalar))) * Ymagnitude\r\ntransUp = transUp - 0\r\nspeedScalar = minSpeedScalar + ((maxSpeedScalar - minSpeedScalar) * rand3)\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('781', 'Paper Airlplane, Zeppelin', 'local randscalar = 100\r\nlocal timescalar = 100\r\nlocal wavefreqscalar = 50\r\nlocal yawlimit = 60\r\nlocal rolllimit = 25\r\nlocal minSpeedScalar = 1.0\r\nlocal maxSpeedScalar = 1.0\r\n\r\nlocal angle = 0\r\nlocal maxMagnitude = startDistance * .10\r\n\r\nlocal Ymagnitude = 1\r\nlocal Xmagnitude = 3\r\n\r\nlocal modProgress = 4*(-1*(progress*progress) + progress)\r\n\r\nmodelYaw = sin(time*timescalar*rand1) * yawlimit * rand2\r\nmodelRoll = sin(time*timescalar*rand2) * rolllimit * rand1\r\nspeedScalar = minSpeedScalar + ((maxSpeedScalar - minSpeedScalar) * rand3)\r\ntransUp = (sin((rand3 * randscalar * modProgress) + (time * randscalar)) + sin((rand1 * randscalar * modProgress) + (time * wavefreqscalar))) * Ymagnitude\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('801', 'Always Miss', 'transRight = progress * 2\r\ntransUp = progress * 4\r\ntransFront = progress * 20', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('821', 'Orbital Strike (Reverse)', 'local magnitude = totalDistance * 2.0\r\n\r\ntransUp = totalDistance + -magnitude * ( progress )\r\ntransFront = distanceFromImpactPos\r\n\r\n-- speedScalar = 0.8', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('841', 'Drunken Missiles Slow', 'local maxMagnitude = 0.5\r\nlocal minSpeedScalar = .9\r\nlocal maxSpeedScalar = 1.1\r\n\r\nlocal angle = 0\r\nlocal maxArcMagnitude = startDistance * .75\r\n\r\n\r\nlocal magnitude = (progress * 1.9) - 1\r\nmagnitude = (1 - (magnitude * magnitude * magnitude * magnitude)) * maxMagnitude\r\n\r\ntransRight = (sin((rand1 * 1000) + (time * 700)) + cos((rand2 * 1000) + (time * 100))) * magnitude\r\ntransUp = (sin((rand2 * 1000) + (time * 700)) + cos((rand1 * 1000) + (time * 300))) * magnitude\r\nspeedScalar = minSpeedScalar + ((maxSpeedScalar - minSpeedScalar) * rand3)\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxArcMagnitude', '0', '5');
INSERT INTO `spellmissilemotion` VALUES ('861', 'Multi-shot Parabola (4 Missiles)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .50\r\nlocal spread = 5\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n\r\ntransRight = (rand1 - 0.5) * spread * progress\r\ntransUp = (rand2 - 0.5) * spread * progress', '0', '4');
INSERT INTO `spellmissilemotion` VALUES ('881', 'Forward Spin (med) + Parabola (Random low)', 'local angle = 0\r\nlocal randomMagnitudeScalar = rand1\r\n\r\nif (randomMagnitudeScalar <= 0.33)then\r\n	randomMagnitudeScalar = 0.20\r\nelseif (randomMagnitudeScalar <= 0.66)then\r\n	randomMagnitudeScalar = 0.30\r\nelseif (randomMagnitudeScalar <= 0.99)then\r\n	randomMagnitudeScalar = 0.40\r\nend\r\n\r\nlocal maxMagnitude = startDistance * randomMagnitudeScalar\r\nlocal spinRate = 540\r\n\r\nmodelPitch = time * spinRate\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('901', 'Midsummer - Juggle Torch, Self', 'local missileSpeed = 0.42\r\nlocal startSpeed = 20\r\nlocal p0 = 0.5\r\n\r\nlocal travelTime = (startDistance / missileSpeed) - 2.5\r\nlocal v0 = startSpeed\r\nlocal acc = (v0*travelTime + p0) / (travelTime*travelTime)\r\n\r\ntransUp = -acc*time*time + v0*time + p0\r\n\r\nlocal spinRate = 1080\r\nmodelPitch = time * spinRate\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('921', 'Midsummer - Juggle Torch (Quest)', 'local angle = 0\r\nlocal maxMagnitude = (distanceToImpactPos) * 2\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n\r\nlocal spinRate = 1080\r\nmodelPitch = time * spinRate\r\n\r\nspeedScalar = 1', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('922', 'Creature - Encapsulate (Felblaze)', 'scale = 0.10 + 1 * progress * progress\r\n--speedScalar = 3 * progress', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('941', 'Midsummer - Juggle Torch, Slow', 'local missileSpeed = 3.9\r\nlocal startSpeed = 20\r\nlocal p0 = 0\r\n\r\nlocal travelTime = (startDistance / missileSpeed)\r\nlocal v0 = startSpeed\r\nlocal acc = (v0*travelTime + p0) / (travelTime*travelTime)\r\n\r\ntransUp = -acc*time*time + v0*time + p0\r\n\r\n--transFront = -distanceToFirePos\r\n\r\nlocal spinRate = 1420\r\nmodelPitch = time * spinRate\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('942', 'Midsummer - Juggle Torch, Medium', 'local missileSpeed = 6\r\nlocal startSpeed = 15\r\nlocal p0 = 0\r\n\r\nlocal travelTime = (startDistance / missileSpeed)\r\nlocal v0 = startSpeed\r\nlocal acc = (v0*travelTime + p0) / (travelTime*travelTime)\r\n\r\ntransUp = -acc*time*time + v0*time + p0\r\n\r\n--transFront = -distanceToFirePos\r\n\r\nlocal spinRate = 1500\r\nmodelPitch = time * spinRate\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('943', 'Midsummer - Juggle Torch, Fast', 'local missileSpeed = 9\r\nlocal startSpeed = 20\r\nlocal p0 = 0\r\n\r\nlocal travelTime = (startDistance / missileSpeed)\r\nlocal v0 = startSpeed\r\nlocal acc = (v0*travelTime + p0) / (travelTime*travelTime)\r\n\r\ntransUp = -acc*time*time + v0*time + p0\r\n\r\n--transFront = -distanceToFirePos\r\n\r\nlocal spinRate = 1600\r\nmodelPitch = time * spinRate\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('961', 'Creature - Summon Void Sentinel (M\'uru)', 'local degreesPerSec = 720\r\nlocal maxMagnitude = 4\r\n\r\ntransAngle = (missileIndex / missileCount) * 360 + (time * degreesPerSec)\r\ntransMag = 1- progress\r\ntransMag = transMag * maxMagnitude\r\ntransUp = 5 * progress', '0', '5');
INSERT INTO `spellmissilemotion` VALUES ('981', 'Creature - Transform Visual Missile (M\'uru)', 'local sideMagnitude = startDistance * .3\r\nlocal frontMagnitude = startDistance\r\nlocal minAngle = -135\r\nlocal maxAngle = -45\r\nlocal collapseAngle = -90\r\n\r\nspeedScalar = .4 + (progress * 1.2)\r\n\r\ntransAngle = minAngle + (rand1 * (maxAngle - minAngle))\r\ntransAngle = (transAngle * (1 - progress)) + (collapseAngle * progress)\r\ntransMag = sin(progress * 480) * (1 - progress) * sideMagnitude\r\ntransUp = (rand2 - 0.5) * (15 * progress) - 2\r\n\r\ntransFront = sin(progress * 240) * (1 - progress) * frontMagnitude', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1001', 'Parabola (Very VERY High)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .90\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1041', 'Drunken Missiles (High Parabolic)', 'local maxMagnitude = 1.5\r\nlocal minSpeedScalar = .7\r\nlocal maxSpeedScalar = 1.5\r\n\r\nlocal magnitude = (progress * 1.9) - 1\r\nmagnitude = 1 - (magnitude * magnitude * magnitude * magnitude)\r\n\r\ntransRight = (sin((rand1 * 1000) + (time * 1000)) + cos((rand2 * 1000) + (time * 200))) * magnitude\r\ntransUp = (sin((rand2 * 1000) + (time * 700)) + cos((rand1 * 1000) + (time * 300))) * magnitude\r\nspeedScalar = minSpeedScalar + ((maxSpeedScalar - minSpeedScalar) * rand3)\r\n\r\nlocal angle = 0\r\nlocal maxMagnitude = startDistance * .30\r\nlocal spinRate = 360\r\n\r\nmodelPitch = time * spinRate\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude', '0', '5');
INSERT INTO `spellmissilemotion` VALUES ('1061', 'Parabola - Tree Tumble', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .15\r\nlocal spinRate = 120\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n\r\nmodelYaw = time * spinRate\r\nmodelRoll = time * spinRate/2\r\nmodelPitch = time * spinRate/4', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1101', 'Spiral + Parabola (Low, Random)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .05\r\nlocal spinRate = 720\r\n\r\nif ( rand1 > 0.5 ) then\r\n	spinRate = spinRate * -1\r\nend\r\n\r\nmodelRoll = time * spinRate\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1141', 'Parabola (Pitch Spin, High)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .30\r\nlocal spinRate = 720\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n\r\nmodelPitch = time * spinRate\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1161', 'Parabola (Spin, High)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .30\r\nlocal spinRate = 720\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n\r\nmodelPitch = time * spinRate', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1181', 'Parabola (Top Spin, Very High)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .60\r\nlocal spinRate = 360\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n\r\nmodelYaw = time * spinRate\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1183', 'Big to Small to Big Scale (shifted upwards)', 'local m1x=0.4    --the first progress point where the missile is smallest\r\nlocal m1y=0.4    --the scale of the missile at the point above\r\n\r\nlocal m2x=0.6    --the first progress opint where the missile begins growing again\r\nlocal m2y=0.4    --the scale of the missile at the point above\r\n\r\n\r\nlocal slope\r\nlocal intercept\r\nif (progress <m1x) then\r\n                slope=(1-m1y)/(0-m1x)\r\n                intercept=1\r\nelseif (progress<m2x) then\r\n                slope=(m1y-m2y)/(m1x-m2x)\r\n                intercept=m1y-slope*m1x\r\nelse\r\n                slope=(m2y-1)/(m2x-1)\r\n                intercept=1-slope\r\nend\r\nscale=slope*progress+intercept\r\n\r\ntransUp=1.6', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1201', 'Creature - Summon Telestra Clone (Telestra)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .90\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = 2*(1 - (transMag * transMag)) * maxMagnitude', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1221', 'Spiral Cyclone (Slow)', 'local numSpirals = 5\r\nlocal radius = 5 * progress * (rand1 + .5)\r\n\r\nlocal curAngle = numSpirals * progress * 360\r\n\r\ntransFront = (sin(curAngle) * radius) - distanceToFirePos\r\ntransRight = (cos(curAngle) * radius)\r\n\r\ntransUp = 1.5 * progress\r\n\r\nspeedScalar = .2', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1241', 'REUSEME', 'local magnitude = totalDistance * 2\r\nlocal spinRate = 1080\r\n\r\ntransUp = magnitude * ( 1 - progress )\r\ntransFront = distanceToImpactPos\r\nmodelRoll = time * spinRate', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1242', 'Parabola (Pitch Spin, VERY VERY HIGH)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * 6\r\nlocal spinRateP = 60\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n\r\n\r\nmodelPitch = time * spinRateP\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1261', 'Creature - Spirit Burst Extra Visual (Ymiron)', 'local outerWheelSpinRate = 180 	-- 1 spin / sec\r\nlocal outerWheelMag = 2.5			-- 1 yard\r\nlocal missileAngle = outerWheelSpinRate * time\r\n\r\nif (missileIndex > 0) then\r\n	local anglePerMissile = 360 / (missileCount)\r\n	missileAngle = missileAngle + anglePerMissile * missileIndex\r\nend\r\n\r\ntransFront = outerWheelMag * cos ( missileAngle ) * (rand1*30) * time\r\ntransRight = outerWheelMag * sin ( missileAngle ) * (rand2*30) * time\r\n\r\ntransUp = distanceToFirePos*10', '0', '10');
INSERT INTO `spellmissilemotion` VALUES ('1262', 'Creature - Spirit Burst (Ymiron)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .60\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1281', 'Creature - Summon Avenging Spirit Visual (Ymiron)', '\r\n	transUp = (1 - progress) * 8\r\n\r\n\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1301', 'Grizzly Hills - Quest - Burning Oil', '\r\nlocal angle = 0\r\nlocal maxMagnitude = 4\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n\r\n\r\nlocal spread = 1\r\nlocal distanceToFireMin = 5\r\nlocal distanceToFireMax = 30\r\nlocal spreadSpeed = 1\r\nlocal finalSpeed = 1.5\r\n\r\nif ( distanceToFirePos > distanceToFireMin and distanceToFirePos < distanceToFireMax ) then\r\n   speedScalar = spreadSpeed\r\n   if (missileIndex == 0) then\r\n   transUp = spread * ( distanceToFirePos - distanceToFireMin ) / ( distanceToFireMax - distanceToFireMin )\r\n   end\r\n   if (missileIndex == 1) then\r\n   transUp = -spread * ( distanceToFirePos - distanceToFireMin   ) / ( distanceToFireMax - distanceToFireMin )\r\n   end\r\n   if (missileIndex == 2) then\r\n   transRight = spread * ( distanceToFirePos - distanceToFireMin   ) / ( distanceToFireMax - distanceToFireMin )\r\n   end\r\n   if (missileIndex == 3) then\r\n   transRight = -spread * ( distanceToFirePos - distanceToFireMin    ) / ( distanceToFireMax - distanceToFireMin )\r\n   end\r\nend\r\n\r\nif ( distanceToFirePos > distanceToFireMax ) then\r\n   speedScalar = finalSpeed\r\n   if (missileIndex == 0) then\r\n   transUp = spread\r\n   end\r\n   if (missileIndex == 1) then\r\n   transUp = -spread\r\n   end\r\n   if (missileIndex == 2) then\r\n   transRight = spread\r\n   end\r\n   if (missileIndex == 3) then\r\n   transRight = -spread\r\n   end\r\nend', '0', '4');
INSERT INTO `spellmissilemotion` VALUES ('1321', 'Tumbling Debris (Spin, Very High)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .90\r\nlocal spinRate = 1440\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n\r\nmodelPitch = time * spinRate *rand1\r\nmodelYaw = time * spinRate\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1322', 'Tumbling Debris (Very High)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .90\r\nlocal spinRate = 1440\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1341', 'Forward Spin (Med) + Grow (1->3)', 'local spinRate = 540\r\n\r\nmodelPitch = time * spinRate\r\n\r\nscale = 1 + 2 * progress', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1361', 'Parabola (Grow)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .15\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n\r\nscale = progress', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1381', 'Upper Deck - Ethereal Pet OnKill Give Essence', 'local maxHeight = 10\r\n\r\ntransUp = progress * (1 - progress) * maxHeight\r\n\r\n--transFront = startDistance - 2 * distanceToFirePos  --this would reverse the direction of the missile\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1401', 'Scale - 2.00', 'scale = 2', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1421', 'Parabola (Top Spin, Very VERY High)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .60\r\nlocal spinRate = 360\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n\r\nmodelYaw = time * spinRate\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1422', 'Missile Swarm', 'local maxMagnitude = 0.5\r\nlocal minSpeedScalar = 0.7\r\nlocal maxSpeedScalar = 1.5\r\n\r\nlocal magnitude = (progress * 1.9) - 1\r\nmagnitude = 1 - (magnitude * magnitude * magnitude * magnitude)\r\n\r\ntransRight = (sin((rand1 * 1000) + (time * 100)) + cos((rand2 * 1000) + (time * 200))) * magnitude * (1-progress)\r\n--transUp = (sin((rand2 * 1000) + (time * 700)) + cos((rand1 * 1000) + (time * 300))) * magnitude\r\nspeedScalar = minSpeedScalar + ((maxSpeedScalar - minSpeedScalar) * rand3)\r\n\r\n', '0', '5');
INSERT INTO `spellmissilemotion` VALUES ('1441', 'zzOLDCreature - Glare of the Tribunal (Tribunal)', '\r\n	if missileIndex == 1 then\r\n		transRight =  (1 - progress) * 3\r\n	else\r\n		transRight =  (1 - progress) * -3\r\n	end', '0', '2');
INSERT INTO `spellmissilemotion` VALUES ('1461', 'Always Miss (Revised, Random)', 'transRight = 5 * (1 - progress * 2 * rand2)\r\ntransUp = 2 * (1 - progress * 2 * rand1)\r\ntransFront = 80 * progress', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1462', 'Reverse Direction', 'transFront = startDistance - 2 * distanceToFirePos  --this would reverse the direction of the missile\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1481', 'Parabola (Fast Spin, High)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .30\r\nlocal spinRate = 1440\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n\r\nmodelYaw = time * spinRate', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1501', 'Accelerated Missile', 'speedScalar = 0.2 + 2 * progress', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1502', 'Soul Vortex (7 Missiles)', 'local startAngle = 0\r\nlocal degreesPerSec = 180\r\nlocal maxMagnitude = 3\r\nlocal maxKickBack = 10\r\n\r\n--progress = 1 - progress\r\n\r\ntransAngle = startAngle + ((missileIndex / missileCount) * 360) + (time * degreesPerSec)\r\ntransMag = progress\r\ntransMag = (transMag * transMag * 2) - 1\r\ntransMag = (1 - (transMag * transMag))\r\ntransFront = transMag * -maxKickBack\r\ntransMag = transMag * maxMagnitude\r\n\r\n--transUp = distanceToImpactPos - distanceToFirePos', '0', '7');
INSERT INTO `spellmissilemotion` VALUES ('1503', 'Soul Vortex (7 Missiles - Resyncced)', 'local startAngle = 0\r\nlocal degreesPerSec = 180\r\nlocal maxMagnitude = 3\r\nlocal maxKickBack = 10\r\nspeedscalar = 0.5\r\n\r\n--progress = 1 - progress\r\n\r\ntransAngle = startAngle + ((missileIndex / missileCount) * 360) + (time * degreesPerSec)\r\ntransMag = progress\r\ntransMag = (transMag * transMag * 2) - 1\r\ntransMag = (1 - (transMag * transMag))\r\ntransFront = transMag * -maxKickBack\r\ntransMag = transMag * maxMagnitude\r\n\r\n--transUp = distanceToImpactPos - distanceToFirePos', '0', '7');
INSERT INTO `spellmissilemotion` VALUES ('1521', 'Machine Gun', '\r\nif (missileIndex > 0) then\r\n    transFront = progress * (3 - 2 * missileIndex)\r\nend\r\n\r\n', '0', '3');
INSERT INTO `spellmissilemotion` VALUES ('1522', 'Rocket Spiral (x3)', 'local startAngle = 0\r\nlocal degreesPerSec = 180\r\nlocal maxMagnitude = 3\r\nlocal maxKickBack = 10\r\n\r\ntransAngle = startAngle + ((missileIndex / missileCount) * 360) + (time * degreesPerSec)\r\ntransMag = 1 - progress\r\ntransMag = (transMag * transMag * 2) - 1\r\ntransMag = (1 - (transMag * transMag))\r\ntransFront = transMag * -maxKickBack\r\ntransMag = transMag * maxMagnitude\r\n\r\n-- Add Upward Arc\r\ntransUp = (progress * 2) - 1\r\ntransUp = (1 - (transUp * transUp)) * startDistance * .15\r\n\r\ntransFront = transFront + -distanceToFirePos * (1 - progress)', '0', '3');
INSERT INTO `spellmissilemotion` VALUES ('1541', 'Parabola (Pitch and Yaw Spin)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * 0.5\r\nlocal spinRateP = 180\r\nlocal spinRateY = 45\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n\r\n\r\nmodelPitch = time * spinRateP\r\nmodelYaw = time * spinRateY', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1542', 'Parabola (Pitch and Yaw Spin, Low)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * 0.25\r\nlocal spinRateP = 180\r\nlocal spinRateY = 45\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n\r\n\r\nmodelPitch = time * spinRateP\r\nmodelYaw = time * spinRateY', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1561', 'Reverse Test (maybe works?)', 'transMag = ((1 - progress) * distanceToImpactPos) + (progress * -distanceToFirePos)', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1581', 'Parabola (Pitch Spin, slow, low)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .1\r\nlocal spinRate = 120\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n\r\nmodelPitch = time * spinRate\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1601', 'Creature - Raise Dead Effect (Anub\'ar Necromancer)', 'local maxMagnitude = startDistance * .5\r\nlocal spinRate = 360\r\n\r\n\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n\r\nmodelPitch = (rand1 * 5) * (time * spinRate)\r\nspeedScalar = (rand1 + 1)/2.5\r\n\r\ntransUp = rand1 * progress\r\ntransFront = rand2 * progress\r\ntransRight = rand3 * progress\r\n', '0', '5');
INSERT INTO `spellmissilemotion` VALUES ('1621', 'Parabola (Yaw Spin)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * 0.25\r\nlocal spinRateY = 360\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n\r\nmodelYaw = time * spinRateY', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1641', 'Missile Swarm (1 Missile)', 'local maxMagnitude = 0.5\r\nlocal minSpeedScalar = 0.7\r\nlocal maxSpeedScalar = 1.5\r\n\r\nlocal magnitude = (progress * 1.9) - 1\r\nmagnitude = 1 - (magnitude * magnitude * magnitude * magnitude)\r\n\r\ntransRight = (sin((rand1 * 1000) + (time * 100)) + cos((rand2 * 1000) + (time * 200))) * magnitude * (1-progress)\r\n--transUp = (sin((rand2 * 1000) + (time * 700)) + cos((rand1 * 1000) + (time * 300))) * magnitude\r\nspeedScalar = minSpeedScalar + ((maxSpeedScalar - minSpeedScalar) * rand3)\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1661', 'Multi-Shot (2 Missiles)', '-- spread out as the missiles travel\r\nlocal outerWheelMag = 1.5 * progress\r\nlocal missileAngle\r\n\r\n\r\nif (missileIndex > 0) then\r\n	local anglePerMissile = 360 / (missileCount)\r\n	transAngle = anglePerMissile * missileIndex\r\nend\r\n\r\ntransMag = outerWheelMag\r\n', '0', '2');
INSERT INTO `spellmissilemotion` VALUES ('1662', 'Missile - 2', '', '0', '2');
INSERT INTO `spellmissilemotion` VALUES ('1663', 'Forward Spin (Med, Scale = 2)', 'scale = 2\r\nlocal spinRate = 540\r\n\r\nmodelPitch = time * spinRate', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1664', 'Shrink (Less)', 'scale = 1 - (progress / 2)', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1684', 'Creature - Ritual Strike (Svala)', 'local spinRate = 360\r\n\r\nmodelRoll = time * spinRate\r\n\r\ntransUp = progress * 3', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1704', 'Drunken Missiles (2 Missiles)', 'local maxMagnitude = 1.5\r\nlocal minSpeedScalar = .7\r\nlocal maxSpeedScalar = 1.5\r\n\r\nlocal magnitude = (progress * 1.9) - 1\r\nmagnitude = 1 - (magnitude * magnitude * magnitude * magnitude)\r\n\r\ntransRight = (sin((rand1 * 1000) + (time * 1000)) + cos((rand2 * 1000) + (time * 200))) * magnitude\r\ntransUp = (sin((rand2 * 1000) + (time * 700)) + cos((rand1 * 1000) + (time * 300))) * magnitude\r\nspeedScalar = minSpeedScalar + ((maxSpeedScalar - minSpeedScalar) * rand3)\r\n', '0', '2');
INSERT INTO `spellmissilemotion` VALUES ('1724', 'Twin Waves - Double - Large', '\r\nlocal waveHeight = 15\r\nlocal wavesPerSec = 0.3\r\n\r\nif (missileIndex == 0) then\r\ntransRight = waveHeight * sin(time * wavesPerSec * 360)\r\nend\r\n\r\nif (missileIndex == 1) then\r\ntransRight = - waveHeight * sin(time * wavesPerSec * 360)\r\nend\r\n\r\nif (missileIndex == 2) then\r\ntransUp = waveHeight * sin(time * wavesPerSec * 360) /2\r\nend\r\n\r\nif (missileIndex == 3) then\r\ntransUp = - waveHeight * sin(time * wavesPerSec * 360) /2\r\nend', '0', '4');
INSERT INTO `spellmissilemotion` VALUES ('1725', 'Creature - Magic Sickle', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .20\r\nlocal spinRate = -3600\r\n\r\nmodelPitch = time * spinRate\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1726', 'Creature - Summon Harpoon (Skadi)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * 2\r\nlocal spinRate = 1080\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n\r\nmodelPitch = time * spinRate\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1744', 'Creature - Arcane Swarm (Malygos)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * 3\r\n\r\ntransAngle = angle	\r\n\r\nif progress < 0.3 then\r\n	transMag = (1 - (((progress*3.33)-1)^2)) * 15\r\n	speedScalar = .5\r\nelse\r\n	transMag = (1 - (progress*1.43) +0.43) * 15\r\n	speedScalar = 20 * progress * progress * progress\r\nend\r\n\r\n\r\nif progress <= .3 then\r\n	transRight = (cos(progress*3000)) * 2 * (1-progress)\r\n	transUp = (sin(progress*3000)) * 2 * (1-progress)\r\nend', '0', '3');
INSERT INTO `spellmissilemotion` VALUES ('1764', 'Always Miss (Random, JZB)', 'transRight = progress * ( 5 * rand1)\r\ntransUp = progress * ( 4 * rand2)\r\ntransFront = progress * 10\r\n\r\n\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1784', 'Creature - Rock Shards (Archavon)', '	\r\n	modelPitch = -90\r\n--	scale = progress\r\n\r\n--	transRight = (missileIndex * 5) * (1-progress)', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1804', 'Flip Coin, Self', '--[[\r\n\r\n--Old script, was based on \r\n\r\nlocal missileSpeed = 10\r\nlocal startSpeed = 20\r\nlocal p0 = 0.5\r\n\r\nlocal travelTime = (startDistance / missileSpeed)  -- - 2.5\r\nlocal v0 = startSpeed\r\nlocal acc = (v0*travelTime + p0) / (travelTime*travelTime)\r\n\r\n--transUp = -acc*time*time + v0*time + p0\r\n\r\n]]--\r\n\r\nlocal spinRate = 1080\r\nmodelPitch = time * spinRate\r\n\r\n\r\n-- distance = X (totalDistance / 2)\r\n-- acceleration due to gravity = -9.8\r\n-- velocity = v0 + a * t\r\n-- position = p0 + v0 * t + 0.5 a * t * t\r\n\r\nlocal initialPosition = 0;\r\nlocal initialVelocity = 9.8; \r\nlocal initialDistance = startDistance - initialPosition;\r\n\r\nlocal travelTime = initialDistance / initialVelocity;\r\n\r\nlocal t = travelTime * progress\r\n\r\ntransUp = initialPosition + initialVelocity * t + -9.8 * t * t\r\ntransFront = 0', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1824', 'Creature - Shadow Crash (Forgotten One)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .40\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\nmodelRoll = progress * 6000', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1825', 'Engineering - Rocket Turret', 'local startAngle = 0\r\nlocal degreesPerSec = 180\r\nlocal maxMagnitude = 3\r\nlocal maxKickBack = 12\r\n\r\n--progress = 1 - progress\r\nif ( rand1 < 0.5 ) then\r\n	missileIndex = 1;\r\nelse\r\n	missileIndex = 2;\r\nend\r\n\r\ntransAngle = startAngle + ( missileIndex / 2 * 360) + (time * degreesPerSec)\r\ntransMag = progress\r\ntransMag = (transMag * transMag * 2) - 1\r\ntransMag = (1 - (transMag * transMag))\r\ntransFront = transMag * -maxKickBack\r\ntransMag = transMag * maxMagnitude\r\n\r\n--transUp = distanceToImpactPos - distanceToFirePos', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1844', 'Creature - Ember Shower (Sandoval)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .10 + (rand1 * 5)\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\nmodelRoll = progress * 3000', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1864', 'Parabola (Very VERY high, -45 to -0) (bunny jump)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .90\r\nmodelPitch = -45 + 45 * progress\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1865', 'Parabola (Pitch Spin, Very High)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .60\r\nlocal spinRate = 720\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n\r\nmodelPitch = time * spinRate\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1884', 'Multi-Shot (7 Missiles, Rolling, Tight, Drunken)', '-- spread out as the missiles travel\r\nlocal outerWheelMag =  progress / 3\r\nlocal missileAngle\r\n\r\n\r\nlocal maxMagnitude = 1.0\r\nlocal minSpeedScalar = .8\r\nlocal maxSpeedScalar = 1.2\r\n\r\nlocal magnitude = (progress * 1.9) - 1\r\nmagnitude = (1 - (magnitude * magnitude * magnitude * magnitude)) / 3\r\n\r\ntransRight = (sin((rand1 * 1000) + (time * 1000)) + cos((rand2 * 1000) + (time * 200))) * magnitude\r\ntransUp = (sin((rand2 * 1000) + (time * 700)) + cos((rand1 * 1000) + (time * 300))) * magnitude\r\nspeedScalar = minSpeedScalar + ((maxSpeedScalar - minSpeedScalar) * rand3)\r\n\r\n\r\nif (missileIndex > 0) then\r\n	local anglePerMissile = 360 / (missileCount)\r\n	transAngle = anglePerMissile * missileIndex\r\nend\r\n\r\nmodelRoll = (missileIndex + 2) * progress * 360\r\n\r\ntransMag = outerWheelMag\r\n', '0', '7');
INSERT INTO `spellmissilemotion` VALUES ('1904', 'Creature - Arcane Swarm (Malygos)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * 3\r\n\r\ntransAngle = angle	\r\n\r\nif progress < 0.3 then\r\n	transMag = (1 - (((progress*3.33)-1)^2)) * 15\r\n	speedScalar = .5\r\n\r\nelse\r\n	transMag = (1 - (progress*1.43) +0.43) * 15\r\n	speedScalar = 20 * progress * progress * progress\r\nend\r\n\r\n\r\nif progress <= .3 then\r\n	transRight = (cos(progress*3000)) * 2 * (1-progress)\r\n	transUp = (sin(progress*3000)) * 2 * (1-progress)\r\nend', '0', '3');
INSERT INTO `spellmissilemotion` VALUES ('1905', 'Creature - Solar Flare (Elder Brightleaf)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * 1\r\n\r\ntransAngle = angle	\r\n\r\nif progress < .3 then	\r\ntransMag = (1 - (((progress*3.33)-1)^2)) * 10\r\n	speedScalar = .3\r\nelse\r\n	transMag = (1 - (progress*1.43) +0.33) * 10\r\n	speedScalar = 20 * progress * progress * progress\r\nend\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1924', 'Spiral + Spin (4 Missiles)', 'local spread = 1.2\r\n\r\nlocal startAngle = 360 * missileIndex / missileCount;\r\nlocal degreesPerSec = 180\r\n\r\ntransAngle = startAngle + (time * degreesPerSec)\r\ntransMag = spread;\r\n\r\nlocal spinRate = 360\r\nmodelRoll = time * spinRate\r\n', '0', '4');
INSERT INTO `spellmissilemotion` VALUES ('1964', 'Spiral Inward (3 Missiles)', 'local outerWheelSpinRate = 180 	-- 1 spin / sec\r\nlocal outerWheelMag = 2.5			-- 1 yard\r\nlocal missileAngle = outerWheelSpinRate * time\r\n\r\nif (missileIndex > 0) then\r\n	local anglePerMissile = 360 / (missileCount)\r\n	missileAngle = missileAngle + anglePerMissile * missileIndex\r\nend\r\n\r\ntransFront = outerWheelMag * cos ( missileAngle ) * (1 - progress) * 2\r\ntransRight = outerWheelMag * sin ( missileAngle ) * (1 - progress) * 2\r\n', '0', '3');
INSERT INTO `spellmissilemotion` VALUES ('1965', 'Creature - Acivate Construct (Ignis)', 'local outerWheelSpinRate = 180 	-- 1 spin / sec\r\nlocal outerWheelMag = 2.5			-- 1 yard\r\nlocal missileAngle = outerWheelSpinRate * time\r\n\r\nif (missileIndex > 0) then\r\n	local anglePerMissile = 360 / (missileCount)\r\n	missileAngle = missileAngle + anglePerMissile * missileIndex\r\nend\r\n\r\ntransFront = outerWheelMag * cos ( missileAngle ) * (1 - progress) * 2 * progress\r\ntransRight = outerWheelMag * sin ( missileAngle ) * (1 - progress) * 2 * progress\r\n\r\n\r\nlocal angle = 0\r\nlocal maxMagnitude = startDistance * .50\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude', '0', '3');
INSERT INTO `spellmissilemotion` VALUES ('1984', 'Creature - Summon Proximity Mines (Mimiron - P1)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .8\r\nlocal spinRate = 540\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n\r\nmodelPitch = time * spinRate\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('1985', 'Creautre - Rocket Strike (Mimiron)', 'local angle = 0\r\nlocal maxMagnitude = 20\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n\r\nspeedScalar = ((progress + .05)^1.5) * startDistance * .2', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('2004', 'Creature - Laser Barrage (Mimiron)', '\r\n	if missileIndex == 1 then\r\n		transRight = (progress * (rand1 - .50) * 10) + .75\r\n		transUp = progress * (rand2 - .70) * 10\r\n	elseif missileIndex == 2 then\r\n		transRight = (progress * (rand2 - .50) * 10) - .75\r\n		transUp = progress * (rand3 - .70) * 10\r\n	else\r\n		transRight = progress * (rand2 - .50) * 10\r\n		transUp = progress * ((rand1 - .70) * 10) + .75\r\n	end\r\n\r\ntransFront = progress * 3', '0', '3');
INSERT INTO `spellmissilemotion` VALUES ('2024', 'Forward Spin (fast) + Parabola', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .15\r\nlocal spinRate = 1080\r\n\r\nmodelPitch = time * spinRate\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('2025', 'Creature - Rapid Burst Effect (Mimiron)', '	if missileIndex == 1 then\r\n		speedScalar = rand1/1.5 + 1\r\n	elseif missileIndex == 2 then\r\n		speedScalar = rand2/1.5 + 1\r\n	else\r\n		speedScalar = rand3/1.5 + 1\r\n	end\r\n\r\n	if missileIndex == 1 then\r\n		transRight = progress * (rand1 - .50) + .5\r\n		transUp = progress * (rand2 - .50)\r\n	elseif missileIndex == 2 then\r\n		transRight = progress * (rand2 - .50) - .5\r\n		transUp = progress * (rand3 - .50)\r\n	else\r\n		transRight = progress * (rand2 - .50)\r\n		transUp = progress * (rand1 - .50) + .5\r\n	end', '0', '3');
INSERT INTO `spellmissilemotion` VALUES ('2044', 'Missile - 3', '', '0', '3');
INSERT INTO `spellmissilemotion` VALUES ('2064', 'Morgan Test', 'local throwHeight = 32;\r\nlocal progressAtFirstBounce = .45;\r\nlocal heightOfFirstBounce = 10;\r\nlocal progressAtSecondBounce = .75;\r\nlocal heightOfSecondBounce = 7;\r\nlocal spinRate = 360\r\n\r\nmodelPitch = time * spinRate\r\ntransUp = throwHeight * progress;\r\n\r\nif (progress < progressAtFirstBounce) then\r\n\r\n	local normalizedProgress = progress / progressAtFirstBounce;\r\n	transUp = transUp - ((normalizedProgress * normalizedProgress) * throwHeight);\r\n\r\nelseif (progress < progressAtSecondBounce) then\r\n\r\n	local normalizedProgress = (progress - progressAtFirstBounce) /\r\n		(progressAtSecondBounce - progressAtFirstBounce);\r\n\r\n	local curHeight = (normalizedProgress * 2) - 1;\r\n	curHeight = (1 - (curHeight * curHeight)) * heightOfFirstBounce;\r\n\r\n	transUp = (transUp - throwHeight) + curHeight;\r\n\r\nelse\r\n\r\n	local normalizedProgress = (progress - progressAtSecondBounce) /\r\n		(1.0 - progressAtSecondBounce);\r\n\r\n	local curHeight = (normalizedProgress * 2) - 1;\r\n	curHeight = (1 - (curHeight * curHeight)) * heightOfSecondBounce;\r\n\r\n	transUp = (transUp - throwHeight) + curHeight;\r\n\r\nend', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('2084', 'Creature - Flame Leviathan - Rockets (Spiral)', 'local maxHeight = 5 + (startDistance * .08)\r\n\r\nlocal newness = 1 - (progress * progress)\r\n\r\ntransAngle = (rand1 * 360) + (time * 400)\r\n\r\nif progress < 0.05 then\r\n	transMag = progress * 40\r\nelseif progress < .1 then\r\n	transMag = 2\r\nelseif progress < .433333333 then\r\n	transMag = 2 * (1 - ((progress - .1) * 3))\r\nend\r\n\r\nlocal transUp1 = (progress * 3.33) - 1\r\ntransUp1 = (1 - (transUp1 * transUp1)) * maxHeight\r\n\r\nlocal transUp2 = (1.43 - (progress * 1.43)) * maxHeight\r\n\r\nif progress < .2 then\r\n	transUp = transUp1\r\nelseif progress < .4 then\r\n	transUp = transUp1 + ((transUp2 - transUp1) * ((progress - .2) * 5))\r\nelse\r\n	transUp = transUp2\r\nend\r\n\r\nlocal accel = progress + .23\r\nspeedScalar = .05 + (8 * accel * accel * accel)', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('2104', 'Boomerang (Return)', 'local angle = -90\r\nlocal maxMagnitude = startDistance * .2\r\nlocal spinRate = 720\r\n\r\nprogress = 1 - progress\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\nmodelYaw = time * spinRate\r\n\r\n\r\ntransFront = distanceToImpactPos - distanceToFirePos\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('2124', 'Creature - Laser Barrage', '\r\n	if missileIndex == 1 then\r\n		transRight = (progress * (rand1 - .50) * 10) + .75\r\n		transUp = progress * (rand2 - .70) * 10\r\n	elseif missileIndex == 2 then\r\n		transRight = (progress * (rand2 - .50) * 10) - .75\r\n		transUp = progress * (rand3 - .70) * 10\r\n	else\r\n		transRight = progress * (rand2 - .50) * 10\r\n		transUp = progress * ((rand1 - .70) * 10) + .75\r\n	end\r\n\r\ntransFront = progress', '0', '3');
INSERT INTO `spellmissilemotion` VALUES ('2144', 'Creature - Summon Magnetic Core (Mimiron - P3)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .4\r\nlocal spinRate = 540\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n\r\nmodelPitch = time * spinRate\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('2164', 'Dan\'s Test Motion', 'transUp = 5', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('2184', 'Isle of Conquest - Place Seaforium Charge', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .15\r\nlocal spinRate = 1080\r\n\r\nmodelPitch = time * spinRate\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('2204', 'Isle of Conquest - Glaive', 'local spinRate = 1080\r\n\r\nmodelYaw = time * spinRate', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('2224', 'Fountain (Flaming Cinder)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .5\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n\r\ntransFront = -distanceToFirePos * (1 - progress)', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('2244', 'Snake (3 Missiles)', 'local waveHeight = .8\r\nlocal wavesPerSec = 2\r\n\r\ntransRight = waveHeight * sin(time * wavesPerSec * 360) * ( 1 - progress ) * 2', '0', '3');
INSERT INTO `spellmissilemotion` VALUES ('2284', 'Isle of Conquest - Blade Salvo (Glaive Thrower)', 'modelPitch = 90\r\nlocal spinRate = 1080\r\n\r\nmodelYaw = time * spinRate', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('2304', 'Isle of Conquest - Dagger Throw (Generals)', 'local spinRate = 1080\r\n\r\nmodelPitch = time * spinRate', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('2344', 'Parabola (High, Pitch Spin)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .3\r\nlocal spinRate = 720\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n\r\nmodelPitch = time * spinRate\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('2384', 'Spiral Cyclone JS', 'local numSpirals = 2\r\nlocal radius = 5 * progress * (rand1 + 0.5)\r\n\r\nlocal curAngle = numSpirals * progress * 360\r\n\r\ntransFront = (sin(curAngle) * radius) - distanceToFirePos\r\ntransRight = (cos(curAngle) * radius)\r\n\r\ntransUp = 2 * progress', '0', '2');
INSERT INTO `spellmissilemotion` VALUES ('2404', 'Spiral Flat JS', 'local numSpirals = 5\r\nlocal minRadius = 10\r\nlocal radius = minRadius + (10 * progress * (rand1 * 5))\r\n\r\nlocal curAngle = numSpirals * progress * 360\r\n\r\ntransFront = (sin(curAngle) * radius) - distanceToFirePos\r\ntransRight = (cos(curAngle) * radius)\r\n\r\ntransUp = rand2 * 5', '0', '3');
INSERT INTO `spellmissilemotion` VALUES ('2424', 'Drunken Fountain (5 Missiles)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .5\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n\r\ntransFront = -distanceToFirePos * (1 - progress)\r\n\r\nlocal magnitude = transMag * .15\r\n\r\ntransRight = (sin((rand1 * 1000) + (time * 400)) + cos((rand3 * 1000) + (time * 60))) * magnitude\r\ntransUp = (sin((rand2 * 1000) + (time * 300)) + cos((rand1 * 1000) + (time * 100))) * magnitude\r\ntransFront = transFront +\r\n	(sin((rand3 * 1000) + (time * 300)) + cos((rand2 * 1000) + (time * 100))) * magnitude\r\n\r\nspeedScalar = 1 - (progress * .5)', '0', '5');
INSERT INTO `spellmissilemotion` VALUES ('2444', 'Creature - Summon Ice Ring (Arthas Encounter)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .8\r\n--local spinRate = 1080\r\n\r\n--transAngle = angle\r\n--transMag = (progress * 2) - 1\r\n--transMag = (1 - (transMag * transMag)) * maxMagnitude\r\n--transUp = progress * 1.1\r\ntransUp = 20 + (progress * -19)\r\ntransFront = 3 + (progress * -3)\r\n\r\n--modelPitch = time * spinRate\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('2464', 'Forward Spin (fast) + Parabola + Grow (1 -> 3)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .15\r\nlocal spinRate = 1080\r\n\r\nmodelPitch = time * spinRate\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n\r\nscale = 1 + 2 * progress', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('2484', 'Soul Vortex (10 Missiles - No Kickback)', 'local startAngle = 0\r\nlocal degreesPerSec = 180\r\nlocal maxMagnitude = 2.5\r\nlocal maxKickBack = 0\r\n\r\n--progress = 1 - progress\r\n\r\ntransAngle = startAngle + ((missileIndex / missileCount) * 360) + (time * degreesPerSec)\r\ntransMag = progress\r\ntransMag = (transMag * transMag * 2) - 1\r\ntransMag = (1 - (transMag * transMag))\r\ntransFront = transMag * -maxKickBack\r\ntransMag = transMag * maxMagnitude\r\n\r\n--transUp = distanceToImpactPos - distanceToFirePos', '0', '10');
INSERT INTO `spellmissilemotion` VALUES ('2504', 'Creature - Soul Reaper Effect (Arthas Encounter)', 'local outerWheelSpinRate = 180 	-- 1 spin / sec\r\nlocal outerWheelMag = 1			-- 1 yard\r\nlocal missileAngle = outerWheelSpinRate * time\r\n\r\nif (missileIndex > 0) then\r\n	local anglePerMissile = 360 / (missileCount)\r\n	missileAngle = missileAngle + anglePerMissile * missileIndex\r\nend\r\n\r\ntransFront = outerWheelMag * cos ( missileAngle ) * (1 - progress) * 2\r\ntransRight = outerWheelMag * sin ( missileAngle ) * (1 - progress) * 2\r\n', '0', '3');
INSERT INTO `spellmissilemotion` VALUES ('2544', 'Stinger Missile (always arrive in ~7 sec)', '\r\ntransAngle = 0	\r\n\r\nif (time < 7) then\r\n	speedAbs = distanceToImpactPos / (7 - time)\r\nelse\r\n	speedAbs = 100000\r\nend\r\n\r\nif progress < 0.4 then\r\n	transMag = (1 - (((progress*3.33)-1)^2)) * 20\r\n	speedAbs = speedAbs * 0.4\r\nelseif progress < 0.9 then\r\n	transMag = (1 - (progress*1.43) +0.43) * 20\r\n	speedAbs = speedAbs * (progress^2)\r\nelse\r\n	transMag = (1 - (progress*1.43) +0.43) * 20\r\nend\r\n\r\n', '0', '3');
INSERT INTO `spellmissilemotion` VALUES ('2564', 'Spiral + Spin (2 Missiles)', 'local spread = 1.2\r\n\r\nlocal startAngle = 360 * missileIndex / missileCount;\r\nlocal degreesPerSec = 180\r\n\r\ntransAngle = startAngle + (time * degreesPerSec)\r\ntransMag = spread;\r\n\r\nlocal spinRate = 360\r\nmodelRoll = time * spinRate\r\n', '0', '2');
INSERT INTO `spellmissilemotion` VALUES ('2584', 'Fast Spiral + Spin (4 Missiles)', 'local spread = .5\r\n\r\nlocal startAngle = 360 * missileIndex / missileCount;\r\nlocal degreesPerSec = 360\r\n\r\ntransAngle = startAngle + (time * degreesPerSec)\r\ntransMag = spread;\r\n\r\nlocal spinRate = 360\r\nmodelRoll = time * spinRate\r\n', '0', '4');
INSERT INTO `spellmissilemotion` VALUES ('2624', 'Drunken Fountain (1 Missile)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .5\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n\r\ntransFront = -distanceToFirePos * (1 - progress)\r\n\r\nlocal magnitude = transMag * .15\r\n\r\ntransRight = (sin((rand1 * 1000) + (time * 400)) + cos((rand3 * 1000) + (time * 60))) * magnitude\r\ntransUp = (sin((rand2 * 1000) + (time * 300)) + cos((rand1 * 1000) + (time * 100))) * magnitude\r\ntransFront = transFront +\r\n	(sin((rand3 * 1000) + (time * 300)) + cos((rand2 * 1000) + (time * 100))) * magnitude\r\n\r\nspeedScalar = 1 - (progress * .5)', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('2644', 'Creature - Gunship Cannon Fire (Arthas Dungeon)', 'transUp = (progress * (rand1 - .5)) * 20\r\ntransRight = (progress * (rand2 - .5)) * 20\r\n\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('2645', 'Creature - Ice Bomb (Sindragosa)', 'local angle = 0\r\nlocal maxMagnitude = 20\r\n\r\nlocal angle = 0\r\nlocal maxMagnitude = startDistance * .10\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\nspeedAbs = totalDistance/5.5', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('2664', 'Spirtal + Spin', 'local spread = 1.2\r\n\r\nlocal startAngle = 360 * missileIndex / missileCount;\r\nlocal degreesPerSec = 180\r\n\r\ntransAngle = startAngle + (time * degreesPerSec)\r\ntransMag = spread;\r\n\r\nlocal spinRate = 360\r\nmodelRoll = time * spinRate\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('2684', 'Icecrown Dungeon - Destroy Wall, Sylvanas', 'transUp = ((progress * (rand1 - .5)) * 5) + (progress * 5)\r\ntransRight = (progress * (rand2 - .5)) * 20', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('2704', 'Fast Spiral + Spin (1 Missile)', 'local spread = .5\r\n\r\nlocal startAngle = 360 * missileIndex / missileCount;\r\nlocal degreesPerSec = 360\r\n\r\ntransAngle = startAngle + (time * degreesPerSec)\r\ntransMag = spread;\r\n\r\nlocal spinRate = 360\r\nmodelRoll = time * spinRate\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('2744', 'Triple Parabola (Medium)', 'local angle = 1\r\nlocal maxMagnitude = startDistance * .20\r\n\r\ntransAngle = angle\r\nprogress = math.fmod(progress * 3, 1)\r\ntransMag = (progress * 2) - 1\r\ntransMag = (.85 - (transMag * transMag)) * maxMagnitude', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('2764', 'Stinger Missile (No speed mod)', '\r\ntransAngle = 0	\r\n\r\n--speedAbs = startDistance / 7.5\r\n\r\nif progress < 0.4 then\r\n	transMag = (1 - (((progress*3.33)-1)^2)) * 20\r\n	speedAbs = speedAbs * .5\r\nelse\r\n	transMag = (1 - (progress*1.43) +0.43) * 20\r\n	speedAbs = speedAbs * (1.2+progress)^3\r\nend\r\n\r\n', '0', '3');
INSERT INTO `spellmissilemotion` VALUES ('2784', 'Parabola (Medium)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .20\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('2804', 'Forward Spin + Triple Parabola (Low)', 'local angle = 1\r\nlocal maxMagnitude = startDistance * .20\r\nlocal spinRate = 360\r\n\r\n\r\ntransAngle = angle\r\nprogress = math.fmod(progress * 3, 1)\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\nmodelPitch = time * spinRate', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('2824', 'Drunken Fountain (3 Missiles)', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .5\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n\r\ntransFront = -distanceToFirePos * (1 - progress)\r\n\r\nlocal magnitude = transMag * .15\r\n\r\ntransRight = (sin((rand1 * 1000) + (time * 400)) + cos((rand3 * 1000) + (time * 60))) * magnitude\r\ntransUp = (sin((rand2 * 1000) + (time * 300)) + cos((rand1 * 1000) + (time * 100))) * magnitude\r\ntransFront = transFront +\r\n	(sin((rand3 * 1000) + (time * 300)) + cos((rand2 * 1000) + (time * 100))) * magnitude\r\n\r\nspeedScalar = 1 - (progress * .5)', '0', '3');
INSERT INTO `spellmissilemotion` VALUES ('2825', 'Spiral + Parabola', 'local waveHeight = 1\r\nlocal wavesPerSec = 2\r\nlocal angle = 2\r\nlocal maxMagnitude = startDistance * .15\r\nlocal spinRate = 720\r\n\r\nmodelRoll = time * spinRate\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('2828', 'Drunken Missiles (1 Missile)', 'local maxMagnitude = 1.5\r\nlocal minSpeedScalar = .7\r\nlocal maxSpeedScalar = 1.5\r\n\r\nlocal magnitude = (progress * 1.9) - 1\r\nmagnitude = 1 - (magnitude * magnitude * magnitude * magnitude)\r\n\r\ntransRight = (sin((rand1 * 1000) + (time * 1000)) + cos((rand2 * 1000) + (time * 200))) * magnitude\r\ntransUp = (sin((rand2 * 1000) + (time * 700)) + cos((rand1 * 1000) + (time * 300))) * magnitude\r\nspeedScalar = minSpeedScalar + ((maxSpeedScalar - minSpeedScalar) * rand3)\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('2830', 'Creature - Nightmares (Green Dragon Encounter)', 'modelPitch = 90', '0', '3');
INSERT INTO `spellmissilemotion` VALUES ('2831', 'Spiral (Small) Flat', 'local radius = (progress * 8)\r\n\r\nlocal curAngle = progress * 90\r\n\r\ntransFront = (sin(curAngle) * radius) - distanceToFirePos\r\ntransRight = (cos(curAngle) * radius)', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('2832', 'Spiral Vortex (4 Missiles) (Tight, Don\'t Spiral)', 'local startAngle = 45\r\nlocal degreesPerSec = 0\r\nlocal maxMagnitude = 1.75\r\nlocal maxKickBack = 5\r\n\r\ntransAngle = startAngle + ((missileIndex / missileCount) * 360) + (time * degreesPerSec)\r\ntransMag = 1 - progress\r\ntransMag = (transMag * transMag * 2) - 1\r\ntransMag = (1 - (transMag * transMag))\r\ntransFront = transMag * -maxKickBack\r\ntransMag = transMag * maxMagnitude\r\n', '0', '4');
INSERT INTO `spellmissilemotion` VALUES ('2833', 'Festergut - Malleable Ooze', 'local throwHeight = 32.5;\r\nlocal progressAtFirstBounce = .45;\r\nlocal heightOfFirstBounce = 10;\r\nlocal progressAtSecondBounce = .75;\r\nlocal heightOfSecondBounce = 7;\r\nlocal spinRate = 360\r\n\r\nmodelPitch = time * spinRate\r\ntransUp = throwHeight * progress;\r\n\r\nif (progress < progressAtFirstBounce) then\r\n\r\n	local normalizedProgress = progress / progressAtFirstBounce;\r\n	transUp = transUp - ((normalizedProgress * normalizedProgress) * throwHeight);\r\n\r\nelseif (progress < progressAtSecondBounce) then\r\n\r\n	local normalizedProgress = (progress - progressAtFirstBounce) /\r\n		(progressAtSecondBounce - progressAtFirstBounce);\r\n\r\n	local curHeight = (normalizedProgress * 2) - 1;\r\n	curHeight = (1 - (curHeight * curHeight)) * heightOfFirstBounce;\r\n\r\n	transUp = (transUp - throwHeight) + curHeight;\r\n\r\nelse\r\n\r\n	local normalizedProgress = (progress - progressAtSecondBounce) /\r\n		(1.0 - progressAtSecondBounce);\r\n\r\n	local curHeight = (normalizedProgress * 2) - 1;\r\n	curHeight = (1 - (curHeight * curHeight)) * heightOfSecondBounce;\r\n\r\n	transUp = (transUp - throwHeight) + curHeight;\r\n\r\nend', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('2834', 'Creature - Broken Frostmourne Soul Missiles (Arthas Enc', 'local numSpirals = 5\r\nlocal minRadius = 10\r\nlocal radius = minRadius + (10 * progress * (rand1 * 2))\r\n\r\nlocal curAngle = numSpirals * progress * -360\r\n\r\ntransFront = ((sin(curAngle) * radius * rand3)) * progress\r\ntransRight = (cos(curAngle) * radius * rand3) * progress\r\n\r\ntransUp = (rand2 * 5)* progress\r\n\r\nscale = (rand2 + 1) * 2', '0', '3');
INSERT INTO `spellmissilemotion` VALUES ('2835', 'Random Scale (1->2)', 'scale = 1 + 1*rand1', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('2836', 'Creature - Player Wins, Frostmourne Room - Missiles', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .35\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n\r\ntransFront = -distanceToFirePos * (1 - progress)\r\n\r\nlocal magnitude = transMag * .15\r\n\r\ntransRight = (sin((rand1 * 1000) + (time * 400)) + cos((rand3 * 1000) + (time * 60))) * magnitude\r\ntransUp = (sin((rand2 * 1000) + (time * 300)) + cos((rand1 * 1000) + (time * 100))) * magnitude\r\ntransFront = transFront +\r\n	(sin((rand3 * 1000) + (time * 300)) + cos((rand2 * 1000) + (time * 100))) * magnitude\r\n\r\nspeedScalar = 1 - (progress * .5)', '0', '3');
INSERT INTO `spellmissilemotion` VALUES ('2837', 'Icecrown Raid - Arthas - Frostmoune Breaks', 'local angle = 0\r\nlocal maxMagnitude = startDistance * .75\r\nlocal spinRate = 540\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\n\r\nmodelPitch = time * spinRate *rand1\r\nmodelYaw = time * spinRate\r\n', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('2839', 'Snake (half amp, rand wave)', 'local waveHeight = .2\r\nlocal wavesPerSec = 2 + (rand1 * 3)\r\n\r\ntransRight = waveHeight * sin(time * wavesPerSec * 360) * ( 1 - progress ) * 2', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('2840', 'Stinger Missile (always arrive in ~5 sec)', '\r\ntransAngle = 0	\r\n\r\nif (time < 5) then\r\n	speedAbs = distanceToImpactPos / (5 - time)\r\nelse\r\n	speedAbs = 100000\r\nend\r\n\r\nif progress < 0.4 then\r\n	transMag = (1 - (((progress*3.33)-1)^2)) * 20\r\n	speedAbs = speedAbs * 0.4\r\nelseif progress < 0.9 then\r\n	transMag = (1 - (progress*1.43) +0.43) * 20\r\n	speedAbs = speedAbs * (progress^2)\r\nelse\r\n	transMag = (1 - (progress*1.43) +0.43) * 20\r\nend\r\n\r\n', '0', '3');
INSERT INTO `spellmissilemotion` VALUES ('2841', 'Creature - Meteor Strike (Halion)', 'local angle = 0\r\nlocal maxMagnitude = 20\r\n\r\nlocal angle = 0\r\nlocal maxMagnitude = startDistance * .10\r\n\r\ntransAngle = angle\r\ntransMag = (progress * 2) - 1\r\ntransMag = (1 - (transMag * transMag)) * maxMagnitude\r\nspeedAbs = totalDistance/6.5', '0', '1');
INSERT INTO `spellmissilemotion` VALUES ('2853', 'Creature - Tsunami (Throne of Tides)', '	scale = (1/(progress+.2))', '0', '1');
