-- MySQL dump 10.13  Distrib 5.6.9-rc, for Win64 (x86_64)
--
-- Host: localhost    Database: unused
-- ------------------------------------------------------
-- Server version	5.6.9-rc

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `worldstateui`
--

DROP TABLE IF EXISTS `worldstateui`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `worldstateui` (
  `Id` int(10) NOT NULL DEFAULT '0',
  `Map` int(10) NOT NULL DEFAULT '0',
  `Zone` int(10) NOT NULL DEFAULT '0',
  `PhaseShift` int(10) NOT NULL DEFAULT '0',
  `Icon` varchar(58) NOT NULL DEFAULT '',
  `Text` varchar(200) NOT NULL DEFAULT '',
  `Text_loc2` varchar(200) NOT NULL DEFAULT '',
  `Description` varchar(200) NOT NULL DEFAULT '',
  `Description_loc2` varchar(200) NOT NULL DEFAULT '',
  `StateVariable` int(10) NOT NULL DEFAULT '0',
  `Type` int(10) NOT NULL DEFAULT '0',
  `DynamicIcon` varchar(100) NOT NULL DEFAULT '',
  `DynamicTooltip` varchar(100) NOT NULL DEFAULT '',
  `DynamicTooltip_loc2` varchar(100) NOT NULL DEFAULT '',
  `ExtendedUI` int(10) NOT NULL DEFAULT '0',
  `ExtendedUIStateVariable1` int(10) NOT NULL DEFAULT '0',
  `ExtendedUIStateVariable2` int(10) NOT NULL DEFAULT '0',
  `ExtendedUIStateVariable3` int(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `Id` (`Id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `worldstateui`
--

LOCK TABLES `worldstateui` WRITE;
/*!40000 ALTER TABLE `worldstateui` DISABLE KEYS */;
/*!40000 ALTER TABLE `worldstateui` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Records of `worldstateui`
--

INSERT INTO `worldstateui` VALUES ('220', '0', '0', '64', 'Interface\\WorldStateFrame\\DreadLordIcon', 'The enemy controls the Undercity!', 'L\'ennemi contrôle Fossoyeuse !', 'Varimathras and Grand Apothecary Putress have taken over the Undercity!', 'Varimathras et le grand apothicaire Putrescin se sont emparés de Fossoyeuse !', '3878', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('233', '0', '0', '128', 'Interface\\WorldStateFrame\\SkullBones', 'The enemy controls the Undercity!', 'L\'ennemi contrôle Fossoyeuse !', 'Grand Apothecary Putress and Varimathras have taken over the Undercity!', 'Le grand apothicaire Putrescin et Varimathras se sont emparés de Fossoyeuse !', '3963', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('260', '0', '0', '256', 'Interface\\TargetingFrame\\UI-PVP-Alliance', 'Operation Gnomeregan is in progress.', 'L\'opération Gnomeregan est en cours.', 'Operation Gnomeregan is in progress.', 'L\'opération Gnomeregan est en cours.', '4981', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('264', '0', '0', '256', 'Interface\\TargetingFrame\\UI-PVP-Alliance', 'The Gnomes control the airfield!', 'Les gnomes contrôlent l\'aérodrome !', 'The Gnomes control the airfield!', 'Les gnomes contrôlent l\'aérodrome !', '5044', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('266', '0', '0', '256', 'Interface\\TargetingFrame\\UI-PVP-Alliance', 'The Gnomes control the airfield and command post.', 'Les gnomes contrôlent l\'aérodrome et le poste de commandement.', 'The Gnomes have secured the airfield and the surface command post.', 'Les gnomes ont sécurisé l\'aérodrome et le poste de commandement de la surface.', '5043', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('268', '0', '0', '256', 'Interface\\TargetingFrame\\UI-PVP-Alliance', 'The Gnomes control the surface of Gnomeregan.', 'Les gnomes contrôlent la surface de Gnomeregan.', 'The entrance to Gnomeregan, command post and airfield are secure.', 'L\'entrée de Gnomeregan, l\'aérodrome et le poste de commandement sont sécurisés.', '5045', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('270', '0', '0', '256', 'Interface\\TargetingFrame\\UI-PVP-Alliance', 'The tunnels of Gnomeregan are secured.', 'Les tunnels de Gnomeregan sont sécurisés.', 'The tunnels of Gnomeregan are secured.', 'Les tunnels de Gnomeregan sont sécurisés.', '5011', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('262', '0', '0', '256', 'Interface\\WorldStateFrame\\CombatSwords', 'Assist the Gnomeregan forces at the engineering facilities.', 'Aidez les troupes de Gnomeregan dans le complexe technique.', 'Assist the Gnomeregan forces at the engineering facilities.', 'Aidez les troupes de Gnomeregan dans le complexe technique.', '5018', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('263', '0', '0', '256', 'Interface\\WorldStateFrame\\CombatSwords', 'The airfield is under attack.', 'L\'aérodrome est attaqué.', 'Assist the Gnomeregan forces at the Airfield!', 'Aider les troupes de Gnomeregan à l\'aérodrome !', '5039', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('267', '0', '0', '256', 'Interface\\WorldStateFrame\\CombatSwords', 'The forces are battling over the entrance to Gnomeregan.', 'Les troupes se battent pour l\'entrée de Gnomeregan.', 'Assist the Gnomeregan forces at the entrance to Gnomeregan.', 'Aider les troupes de Gnomeregan à l\'entrée de Gnomeregan.', '5019', '0', 'Interface\\WorldStateFrame\\CombatSwords', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('269', '0', '0', '256', 'Interface\\WorldStateFrame\\CombatSwords', 'The forces are battling in the tunnels of Gnomeregan.', 'Les troupes combattent dans les tunnels de Gnomeregan.', 'Assist the attack force in the tunnels of Gnomeregan.', 'Aider la troupe d\'attaque dans les tunnels de Gnomeregan.', '5021', '0', 'Interface\\WorldStateFrame\\CombatSwords', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('261', '0', '0', '256', '', 'Rocket Launchers Destroyed = %5027w/4', 'Lance-roquettes détruits = %5027w/4', '', '', '5040', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('265', '0', '0', '256', '', 'Tankbusters Destroyed = %5006w/6', 'Explose-chars détruits = %5006w/6', 'Assist the Gnomeregan forces at the engineering facilities.', 'Aidez les troupes de Gnomeregan dans le complexe technique.', '5018', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('217', '0', '0', '64', '', 'The battle for Undercity has begun!', 'La bataille pour Fossoyeuse a commencé !', 'The battle for Undercity has begun!', 'La bataille pour Fossoyeuse a commencé !', '3875', '1', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('218', '0', '0', '64', '', '%3877w minutes until the battle for the Undercity begins!', '%3877w minutes avant le début de la bataille pour Fossoyeuse !', 'Time remaining until the battle for the Undercity begins!', 'Temps restant avant le début de la bataille pour Fossoyeuse !', '3876', '1', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('221', '0', '0', '64', 'Interface\\WorldStateFrame\\CombatSwords', 'The Horde is battling over the courtyard!', 'La Horde se bat pour le contrôle de la cour !', 'Assist the Horde forces in the Undercity courtyard!', 'Aidez les forces de la Horde dans la cour de Fossoyeuse !', '3885', '1', 'Interface\\WorldStateFrame\\CombatSwords', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('222', '0', '0', '64', 'Interface\\TargetingFrame\\UI-PVP-Horde', 'The Horde controls the courtyard!', 'La Horde contrôle la cour !', 'The area is now secured.', 'La zone est maintenant sécurisée.', '3886', '1', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('223', '0', '0', '64', 'Interface\\WorldStateFrame\\CombatSwords', 'The Horde is battling over the inner sanctum!', 'La Horde se bat pour le contrôle du sanctum intérieur !', 'Assist the Horde forces in the Trade Quarter and Canals!', 'Aidez les forces de la Horde dans le quartier des marchands et les canaux !', '3887', '1', 'Interface\\WorldStateFrame\\CombatSwords', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('224', '0', '0', '64', 'Interface\\TargetingFrame\\UI-PVP-Horde', 'The Horde controls the inner sanctum!', 'La Horde contrôle le sanctum intérieur !', 'The area is now secured.', 'La zone est maintenant sécurisée.', '3888', '1', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('225', '0', '0', '64', 'Interface\\WorldStateFrame\\CombatSwords', 'The Horde is battling over the Apothecarium!', 'La Horde se bat pour le contrôle de l\'Apothicarium !', 'Assist the Horde forces in the Apothecarium!', 'Aidez les forces de la Horde dans l\'Apothicarium !', '3891', '1', 'Interface\\WorldStateFrame\\CombatSwords', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('226', '0', '0', '64', 'Interface\\TargetingFrame\\UI-PVP-Horde', 'The Horde controls the Apothecarium!', 'La Horde contrôle l\'Apothicarium !', 'The area is now secured.', 'La zone est maintenant sécurisée.', '3892', '1', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('227', '0', '0', '64', 'Interface\\WorldStateFrame\\CombatSwords', 'The Horde is battling over the Royal Quarter!', 'La Horde se bat pour le contrôle du quartier Royal !', 'Assist the Horde forces in the Royal Quarter!', 'Aidez les forces de la Horde dans le quartier Royal !', '3889', '1', 'Interface\\WorldStateFrame\\CombatSwords', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('228', '0', '0', '64', 'Interface\\TargetingFrame\\UI-PVP-Horde', 'The Horde controls the Royal Quarter! Varimathras is defeated!', 'La Horde contrôle le quartier Royal ! Varimathras est vaincu !', 'The Horde has regained control of the Undercity!', 'La Horde a repris le contrôle de Fossoyeuse !', '3890', '1', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('229', '0', '0', '64', '', '%3893w minute(s) remaining until this event resets.', '%3893w minute(s) avant la réinitialisation de l\'évènement.', '', '', '3894', '1', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('234', '0', '0', '128', 'Interface\\WorldStateFrame\\CombatSwords', 'The Alliance is battling through the Sewers!', 'L\'Alliance se bat dans les égouts !', 'Assist the Alliance forces in the Undercity Sewers!', 'Aidez les forces de l\'Alliance dans les égouts de Fossoyeuse !', '3962', '1', 'Interface\\WorldStateFrame\\CombatSwords', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('235', '0', '0', '128', 'Interface\\TargetingFrame\\UI-PVP-Alliance', 'The Alliance has secured the Sewers!', 'L\'Alliance s\'est emparée des égouts !', 'The area is now secured.', 'La zone est maintenant sécurisée.', '3964', '1', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('236', '0', '0', '128', '', '%3957w minutes until the manhunt begins!', '%3957w minutes avant le début de la chasse à l\'homme !', 'Time remaining until the manhunt for Grand Apothecary Putress begins!', 'Temps restant avant le début de la traque du Grand apothicaire Putrescin.', '3958', '1', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('237', '0', '0', '128', '', 'The manhunt has begun!', 'La chasse à l\'homme a commencé !', 'The manhunt has begun!', 'La chasse à l\'homme a commencé !', '3966', '1', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('238', '0', '0', '128', 'Interface\\WorldStateFrame\\CombatSwords', 'The Alliance is battling through the Apothecarium!', 'L\'Alliance se bat dans l\'Apothicarium !', 'Assist the Alliance forces in the Apothecarium!', 'Aidez les forces de l\'Alliance dans l\'Apothicarium !', '3972', '1', 'Interface\\WorldStateFrame\\CombatSwords', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('239', '0', '0', '128', 'Interface\\TargetingFrame\\UI-PVP-Alliance', 'The Alliance has secured the Apothecarium!', 'L\'Alliance a pris le contrôle de l\'Apothicarium !', 'The area is now secured. Putress has been defeated!', 'La zone est maintenant sécurisée. Putrescin est battu !', '3971', '1', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('271', '0', '0', '256', 'Interface\\TargetingFrame\\UI-PVP-Alliance', '%5037w minutes until Operation: Gnomeregan begins!', '%5037w minutes avant le début de l\'Opération Gnomeregan !', 'Operation: Gnomeregan will commence at this time', 'L\'opération Gnomeregan commencera à ce moment', '5038', '1', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('136', '0', '139', '0', 'Interface\\WorldStateFrame\\AllianceTower', 'Controlled: %2327w', 'Contrôlées : %2327w', 'Alliance Towers Controlled', 'Tours contrôlées par l\'Alliance', '0', '1', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('137', '0', '139', '0', 'Interface\\WorldStateFrame\\HordeTower', 'Controlled: %2328w', 'Contrôlées : %2328w', 'Horde Towers Controlled', 'Tours contrôlées par la Horde', '0', '1', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('138', '0', '139', '0', '', 'Progress: %2427w', 'Progression : %2427w', '', '', '2426', '1', '', '', '', '2718', '2427', '2428', '0');
INSERT INTO `worldstateui` VALUES ('274', '1', '0', '256', 'Interface\\TargetingFrame\\UI-PVP-Horde', 'The Darkspear are prepared to take back the Echo Isles.', 'Les Sombrelances sont prêts à reprendre les îles de l\'Écho.', 'The Darkspear are prepared to take back the Echo Isles.', 'Les Sombrelances sont prêts à reprendre les îles de l\'Écho.', '5052', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('277', '1', '0', '256', 'Interface\\TargetingFrame\\UI-PVP-Horde', 'The trolls have Bwonsamdi on their side!', 'Les trolls ont Bwonsamdi à leurs côtés !', 'The trolls have Bwonsamdi on their side!', 'Les trolls ont Bwonsamdi à leurs côtés !', '5100', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('279', '1', '0', '256', 'Interface\\TargetingFrame\\UI-PVP-Horde', 'The burnt village has been reclaimed!', 'Le village incendié a été repris !', 'The Trolls have eliminated the mindless forces in the burnt village.', 'Les trolls ont éliminé les troupes décérébrées du village incendié.', '5101', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('281', '1', '0', '256', 'Interface\\TargetingFrame\\UI-PVP-Horde', 'Zalazane has fled to another island!', 'Zalazane a fui vers une autre île !', 'The troll forces have forced Zalazane to flee to another island.', 'Les troupes trolles ont forcé Zalazane à fuir vers une autre île.', '5102', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('283', '1', '0', '256', 'Interface\\TargetingFrame\\UI-PVP-Horde', 'Zalazane has been defeated!', 'Zalazane a été vaincu !', 'Zalazane has been defeated!', 'Zalazane a été vaincu !', '5061', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('276', '1', '0', '256', 'Interface\\WorldStateFrame\\CombatSwords', 'Requesting the aid of Bwonsamdi', 'Demander l\'aide de Bwonsamdi', 'Assist the trolls convince Bwonsamdi to help them', 'Aider les trolls à convaincre Bwonsamdi de leur porter secours', '5099', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('278', '1', '0', '256', 'Interface\\WorldStateFrame\\CombatSwords', 'Assist the trolls in taking back the burnt village.', 'Aider les trolls à reprendre le village incendié.', 'Assist the trolls in taking back the burnt village.', 'Aider les trolls à reprendre le village incendié.', '5056', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('280', '1', '0', '256', 'Interface\\WorldStateFrame\\CombatSwords', 'Vol\'jin and his forces are fighting Zalazane.', 'Vol\'jin et ses troupes combattent Zalazane.', 'Vol\'jin and his forces are fighting Zalazane and his hexed troll followers.', 'Vol\'jin et ses troupes combattent Zalazane et ses serviteurs trolls maléficiés.', '5090', '0', 'Interface\\WorldStateFrame\\CombatSwords', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('282', '1', '0', '256', 'Interface\\WorldStateFrame\\CombatSwords', 'The forces are battling Zalazane', 'Les troupes combattent Zalazane', 'The forces are battling Zalazane', 'Les troupes combattent Zalazane', '5060', '0', 'Interface\\WorldStateFrame\\CombatSwords', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('275', '1', '0', '256', 'Interface\\TargetingFrame\\UI-PVP-Horde', '%5071w minutes until Echo Isles takeback begins!', '%5071w minutes avant le début de la reprise des îles de l\'Écho !', 'Echo Isles Takeback will commence at this time', 'La reprise des îles de l\'Écho commencera à ce moment', '5070', '1', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('178', '1', '513', '0', '', '%3082w / 12 Marksmen Remaining', '%3082w / 12 Tireur(s) d\'élite restant(s).', 'Number of Theramore defenders still alive.', 'Nombre de défenseurs de Theramore encore en vie.', '3083', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('126', '1', '1377', '0', 'Interface\\TargetingFrame\\UI-PVP-Alliance', '%2313w/%2317w', '%2313w/%2317w', 'Alliance Silithyst Collected', 'Silithyste collectée par l\'Alliance', '0', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('127', '1', '1377', '0', 'Interface\\TargetingFrame\\UI-PVP-Horde', '%2314w/%2317w', '%2314w/%2317w', 'Horde Silithyst Collected', 'Silithyste collectée par la Horde', '0', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('180', '30', '0', '0', 'Interface\\TargetingFrame\\UI-PVP-Alliance', 'Reinforcements: %3127w', 'Renforts : %3127w', 'Alliance Reinforcements', 'Renforts de l\'Alliance', '3134', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('181', '30', '0', '0', 'Interface\\TargetingFrame\\UI-PVP-Horde', 'Reinforcements: %3128w', 'Renforts : %3128w', 'Horde Reinforcements', 'Renforts de la Horde', '3133', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('63', '30', '0', '0', 'Interface\\WorldStateFrame\\ColumnIcon-GraveyardCapture', 'Graveyards Assaulted', 'Cimetières\r\nattaqués', 'Number of times enemy graveyard banners have been removed', 'Nombre de fois où les bannières des cimetières ennemis ont été saisies', '0', '2', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('65', '30', '0', '0', 'Interface\\WorldStateFrame\\ColumnIcon-GraveyardDefend', 'Graveyards Defended', 'Cimetières\r\ndéfendus', 'Number of times a graveyard capture has been prevented', 'Nombre de fois où la prise d\'un cimetière a été évitée', '0', '2', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('61', '30', '0', '0', 'Interface\\WorldStateFrame\\ColumnIcon-TowerCapture', 'Towers Assaulted', 'Tours attaquées', 'Number of times enemy tower banners have been removed', 'Nombre de fois où les bannières des tours ennemies ont été saisies', '0', '2', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('64', '30', '0', '0', 'Interface\\WorldStateFrame\\ColumnIcon-TowerDefend', 'Towers Defended', 'Tours défendues', 'Number of times a tower capture has been prevented', 'Nombre de fois où la prise d\'une tour a été évitée', '0', '2', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('82', '30', '0', '0', '', 'Secondary Objectives', 'Objectifs secondaires', 'Number of secondary units activated', 'Nombre d\'unités secondaires activées', '0', '2', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('150', '269', '2366', '0', '', 'Medivh\'s Shield Remaining: %2540w%', 'Bouclier de Medivh restant : %2540w%', '', '', '2541', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('171', '269', '2366', '0', '', 'Time Rifts Opened: %2784w/18', 'Failles temporelles ouvertes : %2784w/18', '', '', '2541', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('42', '489', '0', '0', 'Interface\\WorldStateFrame\\ColumnIcon-FlagCapture', 'Flag Captures', 'Drapeaux capturés', 'Number of times you have captured the enemy flag', 'Nombre de fois où vous avez capturé le drapeau ennemi', '0', '2', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('44', '489', '0', '0', 'Interface\\WorldStateFrame\\ColumnIcon-FlagReturn', 'Flag Returns', 'Drapeaux ramenés', 'Number of times you have returned your flag to your base from the field', 'Nombre de fois où vous avez rapporté votre drapeau à la base', '0', '2', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('244', '489', '3277', '0', '', 'Time Remaining: %4248w min.', 'Temps restant : %4248w min.', 'Time Remaining', 'Temps restant', '4247', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('2', '489', '3277', '0', 'Interface\\TargetingFrame\\UI-PVP-Alliance', '%1581w/%1601w', '%1581w/%1601w', 'Alliance flag captures', 'Drapeaux capturés par l\'Alliance', '2339', '0', 'Interface\\WorldStateFrame\\HordeFlag', 'Horde flag has been picked up', 'Le drapeau de la Horde a été pris', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('3', '489', '3277', '0', 'Interface\\TargetingFrame\\UI-PVP-Horde', '%1582w/%1601w', '%1582w/%1601w', 'Horde flag captures', 'Drapeaux capturés par la Horde', '2338', '0', 'Interface\\WorldStateFrame\\AllianceFlag', 'Alliance flag has been picked up', 'Le drapeau de l\'Alliance a été pris', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('101', '529', '0', '0', 'Interface\\TargetingFrame\\UI-PVP-Alliance', 'Bases: %1779w  Resources: %1776w/%1780w', 'Bases : %1779w  Ressources: %1776w/%1780w', 'Alliance status', 'Situation de l\'Alliance', '0', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('102', '529', '0', '0', 'Interface\\TargetingFrame\\UI-PVP-Horde', 'Bases: %1778w  Resources: %1777w/%1780w', 'Bases : %1778w  Ressources: %1777w/%1780w', 'Horde status', 'Situation de la Horde', '0', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('122', '529', '0', '0', 'Interface\\WorldStateFrame\\ColumnIcon-TowerCapture', 'Bases Assaulted', 'Bases attaquées', 'Number of times enemy base banners have been removed', 'Nombre de fois où les bannières de la base ennemie ont été retirées', '0', '2', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('123', '529', '0', '0', 'Interface\\WorldStateFrame\\ColumnIcon-TowerDefend', 'Bases Defended', 'Bases défendues', 'Number of times a base capture has been prevented', 'Nombre de fois où la prise d\'une base a été évitée', '0', '2', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('139', '530', '3483', '0', '', 'Progress: %2427w', 'Progression : %2427w', '', '', '2473', '1', '', '', '', '2718', '2474', '2475', '0');
INSERT INTO `worldstateui` VALUES ('140', '530', '3483', '0', 'Interface\\WorldStateFrame\\AllianceTower', 'Controlled: %2476w', 'Contrôlés : %2476w', 'Alliance Forts Controlled', 'Forts contrôlés par l\'Alliance', '2490', '1', '', 'Last Winner: Alliance', 'Dernier vainqueur : l\'Alliance', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('141', '530', '3483', '0', 'Interface\\WorldStateFrame\\HordeTower', 'Controlled: %2478w', 'Contrôlés : %2478w', 'Horde Forts Controlled', 'Forts contrôlés par la Horde', '2489', '1', '', 'Last Winner: Horde', 'Dernier vainqueur : la Horde', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('144', '530', '3518', '0', 'Interface\\TargetingFrame\\UI-PVP-Horde', 'Guards Remaining: %2491w/%2493w', 'Gardes restants : %2491w/%2493w', '', '', '2503', '1', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('145', '530', '3518', '0', '', 'Progress: %2494w', 'Progrès : %2494w', '', '', '2495', '1', '', '', '', '2718', '2494', '2497', '0');
INSERT INTO `worldstateui` VALUES ('146', '530', '3518', '0', 'Interface\\TargetingFrame\\UI-PVP-Alliance', 'Guards Remaining: %2491w/%2493w', 'Gardes restants : %2491w/%2493w', '', '', '2502', '1', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('163', '530', '3519', '0', '', '', '', '', '', '2623', '0', '', '', '', '2718', '2625', '2624', '0');
INSERT INTO `worldstateui` VALUES ('147', '530', '3519', '0', 'Interface\\WorldStateFrame\\NeutralTower', 'Time Remaining - %2509w:%2512w%2510w', 'Temps restant : %2509w:%2512w%2510w', 'Time remaining until the Spirit Towers become capturable.', 'Temps restant avant que la tour des esprits puisse être capturée.', '2508', '1', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('161', '530', '3519', '0', 'Interface\\WorldStateFrame\\AllianceTower', 'Towers Controlled: %2621w', 'Tours contrôlées : %2621w', 'Alliance Towers Controlled', 'Tours contrôlées par l\'Alliance', '2620', '1', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('162', '530', '3519', '0', 'Interface\\WorldStateFrame\\HordeTower', 'Towers Controlled: %2622w', 'Tours contrôlées : %2622w', 'Horde Towers Controlled', 'Tours de la Horde contrôlées', '2620', '1', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('168', '530', '3519', '0', 'Interface\\WorldStateFrame\\AllianceTower', 'Time Remaining - %2509w:%2512w%2510w', 'Temps restant - %2509w:%2512w%2510w', 'Time remaining until the Spirit Towers become capturable.', 'Temps restant avant que la tour des esprits puisse être capturée.', '2767', '1', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('169', '530', '3519', '0', 'Interface\\WorldStateFrame\\HordeTower', 'Time Remaining - %2509w:%2512w%2510w', 'Temps restant - %2509w:%2512w%2510w', 'Time remaining until the Spirit Towers become capturable.', 'Temps restant avant que la tour des esprits puisse être capturée.', '2768', '1', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('148', '530', '3521', '0', '', '', '', '', '', '2527', '1', '', '', '', '2718', '2528', '2529', '0');
INSERT INTO `worldstateui` VALUES ('149', '530', '3521', '0', '', '', '', '', '', '2533', '1', '', '', '', '2718', '2534', '2535', '0');
INSERT INTO `worldstateui` VALUES ('153', '530', '3521', '0', 'Interface\\WorldStateFrame\\AllianceTower', 'West Beacon', 'Balise ouest', 'Alliance Controlled Beacon', 'Balise contrôlée par l\'Alliance', '2555', '1', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('154', '530', '3521', '0', 'Interface\\WorldStateFrame\\HordeTower', 'West Beacon', 'Balise ouest', 'Horde Controlled Beacon', 'Balise contrôlée par la Horde', '2556', '1', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('155', '530', '3521', '0', 'Interface\\WorldStateFrame\\NeutralTower', 'West Beacon', 'Balise ouest', 'Neutral Controlled Beacon', 'Balise neutre', '2557', '1', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('156', '530', '3521', '0', 'Interface\\WorldStateFrame\\AllianceTower', 'East Beacon', 'Balise est', 'Alliance Controlled Beacon', 'Balise contrôlée par l\'Alliance', '2558', '1', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('157', '530', '3521', '0', 'Interface\\WorldStateFrame\\HordeTower', 'East Beacon', 'Balise est', 'Horde Controlled Beacon', 'Balise contrôlée par la Horde', '2559', '1', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('158', '530', '3521', '0', 'Interface\\WorldStateFrame\\NeutralTower', 'East Beacon', 'Balise est', 'Neutral Controlled Beacon', 'Balise neutre', '2560', '1', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('173', '530', '3831', '0', '', 'North Warp-Gate: %2880w%', 'Portail dimensionnel nord : %2880w%', '', '', '2889', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('174', '530', '3831', '0', '', 'South Warp-Gate: %2881w%', 'Portail dimensionnel sud : %2881w%', '', '', '2889', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('177', '530', '4008', '0', '', 'Shield Remaining: %3054w%', 'Bouclier restant : %3054w%', 'Percentage of the shield remaining.', 'Pourcentage restant du bouclier', '3055', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('142', '534', '3606', '0', '', 'Invading Enemies = %2454w', 'Envahisseurs = %2454w', 'Number of Invading Enemies in the Horde Base', 'Nombre d\'envahisseurs dans la base de la Horde', '2453', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('143', '534', '3606', '0', '', 'Invading Enemies = %2454w', 'Envahisseurs = %2454w', 'Number of Invading Enemies in the Horde Base', 'Nombre d\'envahisseurs dans la base de l\'Alliance', '2486', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('172', '534', '3606', '0', '', 'Current Wave = %2842w of 8', 'Vague en cours : %2842w sur 8', 'Current Wave', 'Vague en cours', '2842', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('159', '559', '0', '0', '', 'Gold Team: %3601w Players Remaining', 'Équipe dorée : %3601w personnages restants', '', '', '2577', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('160', '559', '0', '0', '', 'Green Team: %3600w Players Remaining', 'Équipe verte : %3600w personnages restants', '', '', '2577', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('165', '560', '2367', '0', '', 'Incendiary Bombs Set = %2436w/5', 'Bombes incendiaires placées = %2436w/5', 'Number of Incendiary Bombs Placed in Durnholde', 'Nombre de bombes incendiaires placées dans Fort-de-Durn', '2436', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('151', '562', '0', '0', '', 'Green Team: %3600w Players Remaining', 'Équipe verte : %3600w personnages restants', '', '', '2547', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('152', '562', '0', '0', '', 'Gold Team: %3601w Players Remaining', 'Équipe dorée : %3601w personnages restants', '', '', '2547', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('164', '566', '0', '0', '', '', '', '', '', '2718', '0', '', '', '', '2718', '2719', '2720', '0');
INSERT INTO `worldstateui` VALUES ('166', '566', '0', '0', 'Interface\\TargetingFrame\\UI-PVP-Alliance', 'Bases: %2752w  Victory Points: %2749w/1600', 'Bases : %2752w  Points de victoire : %2749w/1600', '', '', '2769', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('167', '566', '0', '0', 'Interface\\TargetingFrame\\UI-PVP-Horde', 'Bases: %2753w  Victory Points: %2750w/1600', 'Bases : %2753w  Points de victoire : %2750w/1600', '', '', '2770', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('183', '566', '0', '0', 'Interface\\WorldStateFrame\\ColumnIcon-FlagCapture2.blp', 'Flag Captures', 'Captures de drapeau', 'Number of times you have captured the flag', 'Nombre de fois où vous avez capturé le drapeau', '0', '2', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('179', '568', '3805', '0', '', 'Time Until Sacrifice: %3106w Min', 'Sacrifice dans : %3106w min.', 'Time remaining until prisoners are killed.', 'Temps restant avant l\'exécution des prisonniers.', '3104', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('184', '571', '0', '0', '', 'Progress: %3467w', 'Progression : %3467w', '', '', '3466', '1', '', '', '', '2718', '3467', '3468', '0');
INSERT INTO `worldstateui` VALUES ('186', '571', '0', '0', '', 'Progress: %2427w', 'Progression : %2427w', '', '', '3501', '1', '', '', '', '2718', '3502', '3508', '0');
INSERT INTO `worldstateui` VALUES ('215', '571', '0', '0', 'Interface\\WorldStateFrame\\ColumnIcon-FlagCapture', 'Walls Destroyed', 'Murs détruits', 'Number of times you have destroyed enemy walls.', 'Nombre de fois où vous avez détruit des murs ennemis.', '0', '2', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('216', '571', '0', '0', 'Interface\\WorldStateFrame\\ColumnIcon-FlagCapture', 'Buildings Destroyed', 'Bâtiments détruits', 'Number of times you have destroyed enemy buildings.', 'Nombre de fois où vous avez détruit des bâtiments ennemis.', '0', '2', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('188', '571', '4197', '0', 'Interface\\TargetingFrame\\UI-PVP-Horde', 'Vehicles: %3490w/%3491w', 'Véhicules : %3490w/%3491w', 'Horde status', 'Situation de la Horde', '3710', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('189', '571', '4197', '0', 'Interface\\TargetingFrame\\UI-PVP-Alliance', 'Vehicles: %3680w/%3681w', 'Véhicules : %3680w/%3681w', 'Alliance status', 'Situation de l\'Alliance', '3710', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('210', '571', '4197', '0', 'Interface\\TargetingFrame\\UI-PVP-Alliance', 'Alliance Controlled', 'Contrôle : Alliance', '', '', '3803', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('211', '571', '4197', '0', 'Interface\\TargetingFrame\\UI-PVP-Horde', 'Horde Controlled', 'Contrôle : Horde', '', '', '3802', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('208', '571', '4197', '0', '', 'Time Remaining: %3781k', 'Temps restant : %3781k', 'Game ends after this duration', 'La partie s\'achève à la fin de ce temps.', '3710', '3', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('212', '571', '4197', '0', '', 'Next Battle: %4354k', 'Prochaine bataille : %4354k', 'The War for Lake Wintergrasp will resume after this duration.', 'La guerre pour le lac Joug-d\'hiver reprendra à la fin de ce temps.', '3801', '3', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('175', '572', '0', '0', '', 'Gold Team: %3601w Players Remaining', 'Équipe dorée : %3601w personnages restants', '', '', '3002', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('176', '572', '0', '0', '', 'Green Team: %3600w Players Remaining', 'Équipe verte : %3600w personnages restants', '', '', '3002', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('190', '578', '0', '0', '', 'Centrifuge Constructs: %3486w Remaining', 'Assemblages centrifuges : %3486w restant(s)', '', '', '3524', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('185', '595', '0', '0', '', 'Plagued Crates Revealed = %3480w/5', 'Caisses contaminées découvertes : %3480w/5', 'Number of plagued grain crates revealed.', 'Nombre de caisses de céréales pestiférées découvertes.', '3479', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('187', '595', '0', '0', '', 'Scourge Wave = %3504w/10', 'Vague du Fléau = %3504w/10', 'Number of Scourge waves encountered.', 'Nombre de vagues du Fléau rencontrées.', '3504', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('230', '595', '0', '0', '', 'Time Remaining = %3931w min.', 'Temps restant = %3931w min.', 'Time until Guardian of Time corrupted.', 'Temps jusqu\'à ce que le gardien du Temps soit corrompu.', '3932', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('240', '603', '4273', '0', '', 'Time until Algalon transmits distress signal= %4131w min.', 'Signal de détresse d\'Algalon transmis dans= %4131w min.', 'Time until message sent.', 'Temps restant avant l\'envoi du message.', '4132', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('191', '607', '0', '0', '', 'Progress: %3537w', 'Progression : %3537w', '', '', '3536', '1', '', '', '', '2718', '3537', '3538', '0');
INSERT INTO `worldstateui` VALUES ('232', '607', '0', '0', 'Interface\\WorldStateFrame\\ColumnIcon-FlagCapture', 'Demolishers Destroyed', 'Démolisseurs détruits', 'Number of times you have destroyed a demolisher', 'Nombre de fois où vous avez détruit un démolisseur.', '0', '2', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('231', '607', '0', '0', 'Interface\\WorldStateFrame\\ColumnIcon-FlagCapture', 'Gates Destroyed', 'Portes détruites', 'Number of times you have destroyed a gate', 'Nombre de fois où vous avez détruit une porte.', '0', '2', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('192', '607', '4384', '0', 'Interface\\TargetingFrame\\UI-PVP-Alliance', 'Attacker', 'Attaquant', 'Alliance status', 'Situation de l\'Alliance', '4352', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('193', '607', '4384', '0', 'Interface\\TargetingFrame\\UI-PVP-Horde', 'Defender', 'Défenseur', 'Horde status', 'Situation de la Horde', '4352', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('194', '607', '4384', '0', '', 'End of Round: %3559w:%3560w%3561w', 'Fin du round : %3559w:%3560w%3561w', 'Round ends after this duration', 'Le round se termine à la fin de ce temps', '2889', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('196', '607', '4384', '0', 'Interface\\TargetingFrame\\UI-PVP-Alliance', 'Defender', 'Défenseur', 'Alliance status', 'Situation de l\'Alliance', '4353', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('197', '607', '4384', '0', 'Interface\\TargetingFrame\\UI-PVP-Horde', 'Attacker', 'Attaquant', 'Horde status', 'Situation de la Horde', '4353', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('198', '607', '4384', '0', '', 'Bonus Time: %3559w:%3560w%3561w', 'Bonus temps : %3559w:%3560w%3561w', 'Time left for bonus points', 'Temps restant pour les points bonus', '3571', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('199', '607', '4384', '0', '', 'End of Round: %3559w:%3560w%3561w', 'Fin du round : %3559w:%3560w%3561w', 'Round ends after this duration', 'Le round se termine à la fin de ce temps', '3565', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('247', '607', '4384', '0', '', 'End of Round: %3559w:%3560w%3561w', 'Fin du round : %3559w:%3560w%3561w', 'Round ends after this duration', 'Le round se termine à la fin de ce temps', '3564', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('213', '608', '0', '0', '', 'Prison Seal Integrity: %3815w%', 'Résistance du sceau de la prison : %3815w%', '', '', '3816', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('214', '608', '4415', '0', '', 'Portals Opened: %3810w/18', 'Portails ouverts : %3810w/18', '', '', '3816', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('200', '609', '0', '128', '', 'Forces of the Light Remaining: %3590w', 'Troupes de la Lumière restantes : %3590w', 'Forces of the Light remaining!', 'Troupes de la Lumière restantes !', '3592', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('201', '609', '0', '128', '', 'Forces of the Scourge Remaining: %3591w', 'Troupes du Fléau restantes : %3591w', 'Forces of the Scourge remaining!', 'Troupes du Fléau restantes !', '3592', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('202', '609', '0', '128', '', '%3604w minutes until the battle for Light\'s Hope Chapel begins!', '%3604w minutes avant la bataille de l\'Espoir de Lumière !', 'Time remaining until the battle for Light\'s Hope Chapel begins!', 'Temps restant avant le début de la bataille pour la chapelle de l\'Espoir de Lumière !', '3603', '1', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('203', '609', '0', '128', '', 'The battle for Light\'s Hope Chapel has begun!', 'La bataille pour la chapelle de l\'Espoir de Lumière a commencé !', '', '', '3605', '1', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('204', '617', '0', '0', '', 'Gold Team: %3601w Players Remaining', 'Équipe dorée : %3601w personnages restants', '', '', '3610', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('205', '617', '0', '0', '', 'Green Team: %3600w Players Remaining', 'Équipe verte : %3600w personnages restants', '', '', '3610', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('206', '618', '0', '0', '', 'Gold Team: %3601w Players Remaining', 'Équipe dorée : %3601w personnages restants', '', '', '3610', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('207', '618', '0', '0', '', 'Green Team: %3600w Players Remaining', 'Équipe verte : %3600w personnages restants', '', '', '3610', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('241', '628', '0', '0', 'Interface\\TargetingFrame\\UI-PVP-Alliance', 'Reinforcements: %4226w', 'Renforts : %4226w', 'Alliance Reinforcements', 'Renforts de l\'Alliance', '4221', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('242', '628', '0', '0', 'Interface\\TargetingFrame\\UI-PVP-Horde', 'Reinforcements: %4227w', 'Renforts : %4227w', 'Horde Reinforcements', 'Renforts de la Horde', '4222', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('245', '628', '0', '0', 'Interface\\WorldStateFrame\\ColumnIcon-TowerCapture', 'Bases Assaulted', 'Bases attaquées', 'Number of times enemy base banners have been removed', 'Nombre de fois où les bannières de la base ennemie ont été retirées', '0', '2', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('246', '628', '0', '0', 'Interface\\WorldStateFrame\\ColumnIcon-TowerDefend', 'Bases Defended', 'Bases défendues', 'Number of times a base capture has been prevented', 'Nombre de fois où la prise d\'une base a été évitée', '0', '2', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('250', '631', '0', '0', '', 'Time Until Execution: %4904w Min', 'Temps jusqu\'à exécution : %4904w min', 'Time remaining until Minchar succumbs.', 'Temps restant avant que Minchar succombe.', '4903', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('254', '631', '4859', '0', '', 'Unsuccessful Heroic Attempts until Retreat: %4941w of %4942w', 'Tentatives héroïques ratées avant le repli : %4941w sur %4942w', '', '', '4940', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('253', '631', '4889', '0', '', 'Unsuccessful Heroic Attempts until Retreat: %4941w of %4942w', 'Tentatives héroïques ratées avant le repli : %4941w sur %4942w', '', '', '4940', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('251', '631', '4890', '0', '', 'Unsuccessful Heroic Attempts until Retreat: %4941w of %4942w', 'Tentatives héroïques ratées avant le repli : %4941w sur %4942w', '', '', '4940', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('252', '631', '4891', '0', '', 'Unsuccessful Heroic Attempts until Retreat: %4941w of %4942w', 'Tentatives héroïques ratées avant le repli : %4941w sur %4942w', '', '', '4940', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('255', '631', '4910', '0', '', 'Unsuccessful Heroic Attempts until Retreat: %4941w of %4942w', 'Tentatives héroïques ratées avant le repli : %4941w sur %4942w', '', '', '4940', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('248', '649', '0', '0', '', 'Unsuccessful Attempts Remaining: %4389w', 'Tentatives infructueuses restantes : %4389w', '', '', '4390', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('249', '668', '0', '0', '', 'Spirit Wave = %4882w/10', 'Vague d\'esprit = %4882w/10', 'Number of Spirit waves encountered.', 'Nombre de vagues d\'esprits rencontrées.', '4884', '0', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('272', '724', '0', '32', '', 'Halion\'s corporeality: %5050w%', 'Corporéité de Halion : %5050w%', 'Halion\'s corporeality in this dimension', 'Corporéité de Halion dans cette dimension', '5051', '1', '', '', '', '0', '0', '0', '0');
INSERT INTO `worldstateui` VALUES ('273', '724', '0', '1', '', 'Halion\'s corporeality: %5049w%', 'Corporéité de Halion : %5049w%', 'Halion\'s corporeality in this dimension', 'Corporéité de Halion dans cette dimension', '5051', '1', '', '', '', '0', '0', '0', '0');
